src/dune
src/queue/dune
src/queue/lin_tests.ml
src/stack/dune
src/stack/lin_tests.ml

- each command is protected by a Mutex
- FIXME: commands that should return an `int` return an `int arbitrary`

Linearizability tests for Queue and Stack module

---

.github/workflows/linux-500-workflow.yml
.github/workflows/macosx-500-workflow.yml

`dune` builds and runs tests in parallel.
Since many of these multicore tests are heavily parallel this changes the CI to run only one test at a time (sequentially).
It also adds an error-reporting flag (in an attempt) to align the QCheck and `check_error_count` printing.

Run and print dune CI tests sequentially - not in parallel.

---

README.md
dune
dune-project
lib/dune
lin.opam
src/domainslib/dune
src/dune
src/kcas/dune
src/lockfree/dune
src/neg_tests/dune
src/queue/dune
src/stack/dune
stm.opam

This creates packages containing the `Lin` and `STM` libraries, called `lin` and `stm` respectively. It allows users to install and use these libraries in a simple way, independently of the multicoretests test suite—which is restricted to the `multicoretests` package. It also allows to install `lin` and `stm` without some dependencies of multicoretests such as ounit2, lockfree or ppx_deriving.
The package multicoretests now depends on `lin` and `stm`.

Put Lin and STM libraries in a standalone package

---

multicoretests.opam

Following the discussion in #8. The dependencies have been updated upstream, so it seems safe to remove our ocamlbuild pin.

Remove dependency to ocamlbuild

---

src/neg_tests/CList.ml
src/neg_tests/conclist_test.ml
src/neg_tests/dune
src/neg_tests/lin_tests.ml
src/neg_tests/ref_test.ml

This PR makes a number of cosmetic changes to the neg_tests.
It also fixes a few things
- an error count was off-by-one for conclist_test
- the int CList STM test was run sequentially twice (but not in parallel).

Negtest adjustments

---

README.md

I realized that my own instructions were wrong. Simply running `opam install . --deps-only` and `opam exec -- dune build` leads to the error that packages `lin` and `stm` are not found. One must first install them.
Note that this is due to lin and stm not being part of a public repository. Once they are, we can remove this step.

Fix build instructions in readme

---

README.md
lib/STM.ml
lib/dune
multicorecheck.opam

This cleans-up the old Domainslib experiments from STM.ml
- the domainslib tests and properties are removed
- the README is updated
- the dependency is removed from lib/dune and multicorecheck.opam

Remove Domainslib from STM.ml

---

lib/lin.ml
src/neg_tests/domain_lin_tests.ml
src/neg_tests/dune
src/neg_tests/lin_tests_common.ml
src/neg_tests/thread_lin_tests.ml

This splits the negative tests of Lin into
- Domain tests and
- Thread tests
In order to increase reproducability it then
- uses an allocating, non-tail-recursive `interp_thread` function
- delays the first thread until the second is up and running
- increases the `rep_count`
For the latter I spent a bit of time developing a statistical test to decide whether a candidate change would
constitute an improvement. I then recorded for 10.000 arbitrary `cmd`-triples whether the property would hold,
and used these numbers for a z-statistic test following https://www.itl.nist.gov/div898/handbook/prc/section3/prc33.htm
The three above changes proved to yield statistically significant increases.
Things that didn't pan out
- `Thread.delay` instead of `Thread.yield` to maximize concurrency issues
- …

Increase reproducability of Lin Thread tests

---

src/domain_spawntree.ml

This fixes `domain_spawntree` from failing a test on excessive spawns.
Following an idea from @sabine we match on `Failure "failed to allocate domain"` to recognize this behavior
as acceptable when the test contains excessively many spawns.

Fix domain_spawntree test failure on excessive spawns

---

lib/lin.ml
src/internal/cleanup.ml
src/internal/dune

This fixes #9.
The search for a linearization may explore multiple sequential runs, which each require an `init` and a `cleanup`.
The exploration may stop early and try another combination, which means we cannot simply `cleanup` afterwards.
Instead we call `cleanup` when the exploration of a linearization is done.

Avoid double cleanup in Lin

---

src/domainslib/ws_deque_test.ml

This cleans up src/domainslib/ws_deque_test.ml a bit:
- making the parent domain wait for the spawned child domain
- cleaning up repeat/retries experiments

Clean up ws_deque test

---

lib/lin.ml
src/neg_tests/dune
src/neg_tests/effect_lin_tests.ml

This PR implements an interpretation of `CmdSpec` over fibers.
It includes a user-level scheduler based on effects adapted from
@kayceesrk's slides: https://kcsrk.info/slides/retro_effects_simcorp.pdf
With this PR we are now able to test `Domain`, `Thread`, and `Effect`
executions from the same `CmdSpec` specification (three-for-the-price-of-one!)

Add Fiber-interpretation of CmdSpec

---

lib/dune
lib/lin_api.ml
lib/lin_api.mli
test/dune
test/lin_api.ml

This adds to the `lin` library a new module, `Lin_api`, which is able to generate linearizibility tests from an API description.
Example use (credit goes to @jmid for writing those tests):
```ocaml
module Atomic_spec : Lin_api.ApiSpec = struct
open Lin_api
type t = int Atomic.t
let init () = Atomic.make 0
let cleanup _ = ()
let api =
[ val_ "Atomic.get"             (t @-> returning int)                  Atomic.get;
val_ "Atomic.set"             (t @-> int @-> returning unit)         Atomic.set;
val_ "Atomic.exchange"        (t @-> int @-> returning int)          Atomic.exchange;
val_ "Atomic.fetch_and_add"   (t @-> int @-> returning int)          Atomic.fetch_and_add;
val_ "Atomic.compare_and_set" (t @-> int @-> int @-> returning bool) Atomic.compare_and_set;
val_ "Atomic.incr" …
```

Add API-describing DSL for automated linearizability testing

---

lib/lin.ml

This reduces the number of unnecesary `cpu_relax` calls by introducing a plain interpreter function, `interp_plain`.
For the fun of it, I recorded 10 runs of the `Atomic` test from `src/lin_tests.ml` before and after the change.
It turns out to be a statistically significant improvement:
```
x atomic-before.dat
+ atomic-after.dat
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|             +                                                                                                                            x                                        |
|+      +  +  +   +  +      +      +         +                                                        x …
```

Reduce the number of cpu_relax calls

---

multicoretests.opam
src/domainslib/dune

This fixes #10.
It pin-depends the development version of domainslib until the next release containing ocaml-multicore/domainslib#67.

Reenable domainslib/task_parallel test

---

lib/STM.ml
lib/lin.ml
src/neg_tests/effect_lin_tests.ml

Investigating long running times where the following Thread test took *long* to the point of suspecting a deadlock/infinite loop (or a bug in the run-time):
```
dune exec src/neg_tests/thread_lin_tests.exe -- -v -s 219916560
```
Because of other recent fixes enhancing reproducability, I was able to pin-point the following `cmd` triple:
```ocaml
([(Member 982); (Add_node 919); (Member 443); (Member 66); (Add_node 3); (Add_node 3); (Member 5)],
[(Add_node 9); (Member 64); (Member 5); (Add_node 72); (Add_node 989); (Member 0); (Add_node 4); (Add_node 9); (Add_node 78); (Member 67); (Member 56); (Member 76); (Member 223); (Add_node 6); (Member 89)],
[(Add_node 855); (Add_node 36); (Member 1); (Member 142); (Add_node 6); (Add_node 4); (Member 36); (Member 4); (Member 1); (Add_node 7); …
```

Fix long interleaving times

---

lib/util.ml
src/internal/dune
src/internal/util_print_test.ml
src/lockfree/ws_deque_test.ml

This PR extends `print_triple_vertical` with an option to allow a non-centered sequential prefix.
It then updates src/lockfree/ws_deque_test.ml to use the new printer.
Finally it adds a few basic, internal tests of the printer.

Printer fixing

---

lib/lin.ml
src/neg_tests/effect_lin_tests.ml

This changes the negative effect test to something slightly less hackish:
- These tests now fail with exception `Unhandled`.
- Furthermore they don't depend on the internal state of the tested `ref` or `CList` between test runs (which was terrible),
thus making their behavior easier to reproduce - and shrink.
This fixes #51.

Fix effect example

---

lib/STM.ml
src/buffer/buffer_stm_test.ml
src/neg_tests/dune
src/neg_tests/ref_test.ml

This PR cleans up the STM signature, leaving the `repeat`-`retries` combination property, which has worked well for Lin.
Currently, the numbers are set to `repeat:25` and `retries:15`. We may want to adjust these before merging.
As a bonus
- it adds a negative `int64 ref` test
- removes a bit of whitespace
As an extra bonus, with the changes the `Buffer` test can segfault my local Linux running:
```
$ dune exec src/buffer/buffer_stm_test.exe -- -v -s 81407870
```
I'm therefore curious how the Linux CI reacts...

STM clean-up

---

lib/STM.ml
src/domainslib/chan_tests.ml
src/domainslib/dune
src/lazy/lazy_stm_test.ml

This PR provides an initial implementation STM `precond` support for parallel mode using a generate-and-filter approach.
Following Claessen-al:ICFP09 we keep only `cmd list` triples where all interleavings satisfy all preconditions.
The `precond` implementation is enough to get the second part running:
This part tests the `Domainslib.Chan` module. This requires `precond` to avoid
- `recv` blocking on an empty channel
- `send` blocking on a full channel
For the `Domainslib.Chan` tests, this means that we need to generate around twice as many triples as the test `count`.
I've also checked that the run time of the other STM tests is not affected noticably. For reference we now have the following STM tests:
```
src/atomic/atomic_test.ml
src/buffer/buffer_stm_test.ml           ;; expected to …
```

Initial STM precond fix, add Domainslib.Chan tests

---

.github/workflows/linux-500-workflow.yml
.github/workflows/macosx-500-workflow.yml

This PR switches GitHub actions to the opam alpha repository.

Switch to opam alpha repositories

---

lib/lin_api.ml
lib/lin_api.mli
src/hashtbl/dune
src/hashtbl/lin_tests_dsl.ml

This is an initial port of the `Hashtbl` example to the signature DSL. 
I used this as an illustration at the Tarides presentation on Friday.
It adds `nat_small` to the DSL as part of the PR.

Initial Hashtbl port to DSL

---

lib/util.ml
src/lazy/lazy_stm_test.ml

Following the wrapping with exception handlers in #75 I just noticed that the STM tests were missing similar wrapping.
A bonus commit in the PR adds a definition for `equal_exn` to `Util` to help `deriving eq`.

Lazy STM exception wrapping

---

multicoretests.opam

This PR removes two unneeded pin-depends entries.
Both `sexplib0` and `ppxlib` are now available in the alpha repository.

Reduce pin-depends

---

lib/STM.ml
lib/lin.ml

When the first domain function raises an exception, we risk not joining the second domain. This is bad for reproducability. 
Furthermore, unjoined underlying pthreads at exit can apparently cause crashes on Windows (not good either...).
We fix this by wrapping the function bodies in an exception handler and reraising an exception in the "root domain".
Thanks to @patricoferris for pointing this out :pray:

Wrap domain functions in a handler to ensure proper joining

---

lib/STM.ml
src/hashtbl/dune
src/hashtbl/stm_test.ml

This PR ports the `STM` test of `Hashtbl` from qcstm as I intended to use it for comparison with `Lin`.
Overall, this indicated to me that `STM` could use some caring too.
For example, reusable `res` types in the library would reduce the required input lines.
While porting, I noticed that the printer for sequential test was a simple list printer.
I improved it a bit to print the received results in `res` too.

Hashtbl STM test

---

lib/lin_api.ml
lib/lin_api.mli

This PR adds `int32` and `float` combinators which were missing from `lin_api.ml`

Add int32 and float combinators to lin_api

---

lib/STM.ml
src/atomic/atomic_test.ml
src/buffer/buffer_stm_test.ml
src/buffer/dune
src/domainslib/chan_tests.ml
src/domainslib/dune
src/hashtbl/dune
src/hashtbl/stm_test.ml
src/lazy/lazy_stm_test.ml
src/lockfree/ws_deque_test.ml
src/neg_tests/conclist_test.ml
src/neg_tests/dune
src/neg_tests/ref_test.ml

This is a first attempt to reduce the boilerplate associated with type `res` when defining STM tests. To see what would change concretely for the STM user, one must look at file `src/hashtbl/stm_test.ml`.
For the sake of the example, the possibility of returning values of type `exn` is not implemented in STM, and the test writer had to extend it. This is done by adding a constructor to the extensible type `'a STM.Res.ty`, and specifying how results of this type should be compared and printed.
A value of type `res` is constructed as `Res (spec, v)` where `spec` is a “type specification” which identifies the type of the result and contains the comparison and printing functions, and `v` is a value. For convenience, STM provides combinators to construct type specifications.
Finally, in …

First attempt to reduce boilerplate with type res

---

lib/STM.ml
lib/lin_api.ml

This PR fixes printing of `string`s, `bytes`, and `char`s:
- in STM they were neither escaped, nor wrapped in quotes in the shared `res` printers
- in Lin `string` and `char` arguments were not escaped  (it is still missing bytes ATM)

Fix string, bytes, and char printing

---

lib/lin.ml
lib/lin_api.ml
src/atomic/lin_tests.ml
src/hashtbl/lin_tests.ml
src/internal/cleanup.ml
src/kcas/dune
src/kcas/lin_tests.ml
src/lazy/lazy_lin_test.ml
src/neg_tests/lin_tests_common.ml
src/queue/lin_tests.ml
src/stack/lin_tests.ml

This PR adds shrinking of `cmd` arguments for `Lin` in both "non-DSL mode" and in "DSL mode".
We do so by adding an entry to the interface `val shrink_cmd : cmd Shrink.t`.
For non-DSL mode, this can be trivially satisfied with `Shrink.nil` performing no shrinking.
The PR adds shrinkers to the existing non-DSL tests - except for `Lazy` (where testing and shrinking is already dog-slow).
The DSL mode has me on thinner ice. It was nevertheless instructive to better understand the DSL code base.
@OlivierNicole if you have ideas to avoid the ugly "this-should-not-happen" `failwith`s I'm all ears! :grin: 
I noticed QCheck's `char arbitrary` doesn't shrink so I include a work-around. I'll send a QCheck PR to fix it shortly.
This should take care of the `Lin`-part of #65 - the `STM`-part remains. …

Lin shrinking of `cmd` arguments

---

lib/STM.ml
src/neg_tests/ref_test.ml

This PR adds `cmd` argument shrinking to `STM`.
I tried different ways to express it - and ended up going with this one expressed as shrinking the prefix and suffix separately.
This comes at the cost of interpreting the sequential prefix twice over the model, which seems OK for now.
If no `cmd` shrinker is provided by the user, no shrinking happens.
In this situation the performance should be largely unaffected (let's confirm with the CI log).
Ideally `cmd` argument shrinking could benefit from "deriving_shrinker" (see c-cube/qcheck#191).
As an example, the PR provides a `cmd` shrinker in `neg_test/ref_test.ml`.
Together with #84 this PR fixes #65.

STM cmd shrinking

---

multicorecheck.opam
multicoretests.opam

This PR cleans up the dependencies to the newly released QCheck 0.19, thus reducing the pinned dependencies significantly.

Clean-up dependencies to qcheck>=0.19

---

lib/lin_api.ml
lib/lin_api.mli
src/ephemeron/lin_tests_dsl.ml

This little PR reorganizes and renames some of the `Lin_api` combinators:
- we had both `nat_small` and `small_nat` too many lines apart to notice, so remove the latter and order them thematically (`int*` together and so forth, largely moving from smaller to larger base types)
- rename `pos_int` to `int_pos`
- finally update the `Ephemeron` test to reflect the renaming

Reorganize and rename Lin_api combinators

---

src/neg_tests/dune

This PR temporarily rolls back using the DSL for negative tests of `Thread` on the `runtest` `dune` alias
- until we figure out a better way to consistently trigger `Thread` issues
- so that CI turns green again and thus avoids other potential errors to be missed

Temporarily rollback DSL for Thread neg_test

---

README.md
lib/lin_api.ml
lib/lin_api.mli
src/atomic/dune
src/atomic/lin_tests_dsl.ml
src/hashtbl/dune
src/kcas/dune
src/kcas/lin_tests_dsl.ml
src/lazy/dune
src/lazy/lin_tests_dsl.ml
test/dune

This is a ~work-in-progress~ PR to fix #54.
- For `Atomic` we simply rename the existing example
- Porting `Kcas` required extending the interface of `Lin_api` to allow users to write custom types in signatures
- There's also a port of `Lazy` with a workaround for the lack of function generators
~Missing ports:~
- ~src/neg_tests/*~
- ~src/queue~
- ~src/stack~
*(edit: missing ports in #94)*

Port old Lin tests to combinator DSL

---

src/domainslib/task_more_deps.ml
src/domainslib/task_one_dep.ml
src/domainslib/task_parallel.ml

CI is failing since in `Domainslib`, `num_additional_domains` was renamed to `num_domains`: https://github.com/ocaml-multicore/domainslib/pull/78
This PR updates the tests to use `num_domains` accordingly.
With it, the CI should hopefully go green again... 🤞

Restore CI

---

README.md

This PR
- adds the infinite loop issue triggered by `Bytes` tests
- turns a singular `requires` into plural `require`

Add infinite loop issue triggered by Bytes tests

---

src/bytes/dune
src/bytes/lin_tests_dsl.ml
src/dune

This PR contains Lin_api tests of the `Bytes` module from @naomiiiiiiiii
These are the tests that originally triggered an infinite loop on ARM64.
(The commits should probably be squashed before merging)

Add Lin_api test of Bytes

---

lib/STM.ml
src/array/dune
src/array/stm_tests.ml
src/dune

This PR adds `STM` tests of (parts of) the `Stdlib.Array` module.
To do so, it adds missing combinators for `Seq.t` and `array` to `STM`.
With it one is able to observe, e.g., partial writes:
```
--- Info -----------------------------------------------------------------------
Negative test parallel array test parallel failed as expected (27 shrink steps):
|           
|           
.---------------------.
|                     |           
(Fill (4, 5, 'V'))          To_seq        
+++ Messages ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Messages for test parallel array test parallel:
Results incompatible with linearized model
|                                            
| …
```

Add array tests

---

lib/lin_api.ml
lib/lin_api.mli
src/README.md
src/array/dune
src/array/lin_tests.ml
src/array/lin_tests_dsl.ml

This PR adds `Lin` and `Lin_api` tests of (parts of) the `Array` module.
To do so, it adds missing `array` and `seq` combinators to `Lin_api`.
Finally it updates the test overview in src/README.md.

Add Lin array tests

---

lib/lin_api.ml
lib/lin_api.mli
src/ephemeron/lin_tests_dsl.ml

This PR adjusts the `string` distribution in the `Ephemeron` `Lin_api` tests to generate smaller strings - which will hopefully shrink faster.
To do so, we add `string_small` and `string_small_printable` combinators.

Adjust Ephemeron string distribution in lin_api tests

---

issues/task_issue.ml

This little PR updates `issues/task_issue.ml` with the `Domainslib` renaming from #103 to reestablish a clean build.

Update issues/task_issue.ml with Domainslib renaming to reestablish a clean build

---

src/atomic/stm_tests.ml
src/domain/domain_spawntree.ml
src/domainslib/chan_stm_tests.ml
src/domainslib/task_parallel.ml
src/ephemeron/lin_tests_dsl.ml
src/hashtbl/dune
src/hashtbl/stm_tests.ml
src/lazy/dune
src/neg_tests/ref_stm_tests.ml
src/queue/lin_tests_dsl.ml
src/stack/lin_tests_dsl.ml

The CI runs are starting to take a long time. On recent `main` I see:
- MacOS: 45m-1h 
- Linux: 1h-1h20m
This PR therefore takes a pass over all the tests triggered by `dune runtest -j1 --no-buffer --display=quiet` in an attempt to reduce the time spent.
In most cases this amounts to reducing test `count` of long-running tests.
In `Stack` and `Queue` `Lin_api` tests most time was spent on shrinking the very large `int` arguments generated - so here changing to a generator of smaller numbers should make a difference.
Fingers crossed that the CI run of this PR show some actual speed-ups... :crossed_fingers:

Save CI time

---

lib/lin_api.ml
lib/lin_api.mli

This PR shortens `Lin_api.val_with_freq` to `Lin_api.val_freq` to make signature descriptions with a skewed distribution a little less wordy:
```ocaml
let api =
[ val_ "Hashtbl.clear"    Hashtbl.clear    (t @-> returning unit);
val_ "Hashtbl.add"      Hashtbl.add      (t @-> char @-> int @-> returning unit);
val_freq 3 "Hashtbl.remove"   Hashtbl.remove   (t @-> char @-> returning unit);
... ]
```
compared to
```ocaml
let api =
[ val_ "Hashtbl.clear"    Hashtbl.clear    (t @-> returning unit);
val_ "Hashtbl.add"      Hashtbl.add      (t @-> char @-> int @-> returning unit);
val_with_freq 3 "Hashtbl.remove"   Hashtbl.remove   (t @-> char @-> returning unit);
... ]
```

Shorten Lin_api.val_with_freq to Lin_api.val_freq

---

lib/STM.ml
src/lockfree/ws_deque_test.ml

This PR fixes #106 
Besides adding comments to clarify how the definitions differ from those in `lib/STM.ml` it also
- adds `shrink_triple` to the public interface and
- reuses it to minimize the differences

Clarify lockfree/ws_deque definitions

---

README.md

I was running over the list of issues while preparing slides for the OCaml Workshop talk,
and thought it could be a good idea to annotate each of them
- `new`/`known` - depending on whether an issue turned out to be a new discovery or a known one
- `fixed`/`open` - depending on whether the issue has been fixed or not
For the `In/Out_channel` crash I'm unsure of the current status.
The `utop` issue may very well have been fixed.

Update list of issues with status

---

lib/lin_api.ml

While demoing `Lin_api` at the OCaml Workshop I was reminded that `Lin_api` would print two space characters before every `:` (while `STM` or pure `Lin` wouldn't):
```
Results incompatible with sequential execution
|                      
Hashtbl.add t 'a' 0  : ()          
|                      
.------------------------------------.
|                                    |                      
Hashtbl.add t '_' 0  : ()              Hashtbl.clear t  : ()            
Hashtbl.length t  : 2   
```
This little PR fixes it by letting `show_args` return a `String.list` of arguments, which we can print separated by spaces.
Here's a sample output for your viewing pleasure:
```
Results incompatible with sequential execution
|                     
Hashtbl.replace t 'a' 0 : ()       
| …
```

Fix double space in annotated Lin_api output

---

src/threadomain/dune
src/threadomain/threadomain.ml

These tests generate random trees of spawning nodes (either a domain or a thread) and then joining them in another random pattern
These tests only come with generators, not shrinkers, at the moment. It would be interesting to add some shrinkers if we run into failing examples.

Add tests for domains and threads interactions

---

src/semaphore/dune
src/semaphore/stm_tests.ml

I wonder whether using this is making proper use of the `precond`. Without this, the tests will deadlock, as can be expected, but this prevents exercising the deadlock behaviour.

Add STM tests for Semaphore.Counting

---

lib/util.ml

Adopt in fork_prop_with_timeout the same behaviour as in prop_timeout, namely raising a Timeout exception when the child did end on a SIGALRM signal

Use the Timeout exception in fork_prop_with_timeout

---

src/threadomain/threadomain.ml

Now that the generated join patterns cannot (should not) create deadlocks, remove the timeout so that the property won’t fail just because it ran out of time

Remove timeout in the domains+threads tests

---

lib/STM.ml
src/lockfree/ws_deque_test.ml

This is an attempt to solve issue #36 with no modification of the existing tests (except for `lockfree/ws_deque_test.ml` which benefits from the change)
`STM.Make` exposes a new function `arb_cmds_par_` which is parametirized by three `Spec.cmd QCheck.arbitrary` (granted, the name is far from great).
I have also updated `arb_triple` to `arb_cmds_par` in `lockfree/ws_deque_test.ml` according to the name in `STM`.

give each parts of the program a specific cmd generator

---

.github/workflows/linux-500-trunk-workflow.yml
.github/workflows/linux-500-workflow.yml
.github/workflows/macosx-500-trunk-workflow.yml
.github/workflows/macosx-500-workflow.yml

Tests on native builds should not run for more than 2 hours so a 3-hour timeout will abort failing tests sooner.
Tests on bytecode builds run often above 4 hours so keeping the default 6-hour timeout makes sense

CI: Set up a 3-hour timeout on native runs

---

lib/STM.ml
lib/STM.mli

This PR documents the `STM` module in a corresponding `STM.mli` file.
The majority of the documentation is simply moved from `STM.ml`.

Add documentation for the STM module

---

multicoretests.opam

This PR fixes #150 by bumping the Domainslib dependency to the newly released 0.5.0,
thus allowing us to remove the second-to-last `pin-depends` :tada:

Bump Domainslib requirement

---

src/threadomain/threadomain.ml

The Thread-Domain mash up test is dominant in the CI. For example, it takes
- 364.2s in this Linux native run: https://github.com/jmid/multicoretests/actions/runs/3245244865/jobs/5322519932
- 1855.5s in this bytecode run: https://github.com/jmid/multicoretests/actions/runs/3245244809/jobs/5322519748
This PR reduces the count from 1000 to 500 to save CI time.

Reduce threadomain count

---

lib/lin_api.ml

- `QCheck.char` has already `QCheck.Shrink.char` as a shrinker
- `QCheck.printable_char` have `QCheck.Shrink.printable_char` as
a shrinker, which is the desired behaviour.

Quick fix on char shrinkers

---

src/bigarray/lin_tests_dsl.ml

Tune the frequencies of Bigarray functions so that the generation of a new array is tried less often: we expect a failing test that arise from race conditions, so reducing the frequency of operations that generate new arrays (and take more resources) helps to trigger the failure

Reduce frequencies of operations creating Bigarrays

---

src/bigarray/lin_tests_dsl.ml
src/neg_tests/domain_lin_tests.ml
src/neg_tests/thread_lin_tests.ml

A few tests that are expected to fail fail only really seldom in some configurations (macos or bytecode, for instance). Since negative tests end up as soon as the expected counter-example is found, increasing the counts is only used in cases where it would have failed (to fail) otherwise

Repeat more a few failing tests

---

.github/workflows/linux-500-bytecode-trunk-workflow.yml
.github/workflows/linux-500-bytecode-workflow.yml
.github/workflows/linux-500-trunk-workflow.yml
.github/workflows/linux-500-workflow.yml
.github/workflows/macosx-500-trunk-workflow.yml

Since we see a few runs failing on macOS after merging #157, try to fix the problem by enabling back sandboxing. In the failing runs, no dune cache was found so it should probably not be involved (though enabling dune cache triggers its installation early on in the CI run; could this change how other dependencies are built? :thinking:)

CI: Enable opam sandboxing back

---

lib/lin_api.mli

While discussing with @n-osborne today, we realized that some of the type parameters in `Lin_api` are missing documentation.
This PR documents the four type parameters for `ty` and elaborates a bit on the three `Fun.fn` type parameters.

Document Lin_api's type parameters

---

.github/workflows/common.yml
.github/workflows/linux-500-bytecode-trunk-workflow.yml
.github/workflows/linux-500-bytecode-workflow.yml
.github/workflows/linux-500-trunk-workflow.yml
.github/workflows/linux-500-workflow.yml
.github/workflows/macosx-500-trunk-workflow.yml
.github/workflows/macosx-500-workflow.yml

These commits introduce a `common.yml` workflow with the few parameters that changes from one actual workflow to the other. It makes their general maintenance easier.
While we’re at it, now that new options are shared between all workflows, add the following options:
- possibility to pick a specific commit of the compiler
- possibility to run (various times if wanted) one specific test with one specific seed, that makes it faster to check bugs for reproducibility.
The first commit is a worthy addition all by itself, I might have added too many options afterwards (even if I found them useful).

CI: Share the common part of every CI workflow

---

.github/workflows/gh-pages.yml

I've now created a separate `gh-pages` branch to host documentation on https://jmid.github.io/multicoretests/
This PR adds a workflow to build the documentation and push it to `gh-pages` upon changes to `main`.

Add workflow to build gh-pages

---

README.md

This PR adds the bytecode `Effect` issue to the list of found issues.
While at it, it also updates the status of the `Ephemeron` issue to `fixed`.

Add bytecode effect issue

---

lib/STM_spec.mli

This little PR adds documentation to STM to stress which functions of the user-supplied module are expected to be pure.

Document expected purity in STM

---

doc/example/stm_tests.ml
doc/paper-examples/stm_tests.ml
src/domainslib/chan_stm_tests.ml
src/domainslib/task_more_deps.ml
src/domainslib/task_one_dep.ml
src/domainslib/task_parallel.ml
src/lockfree/ws_deque_test.ml

Having scanned CI logs repeatedly I wished for more uniform test names, so that after a change to `STM` or `Lin_api` it was easier to quickly determine whether a given test had been affected by the change or not.
This PR adjusts some of the less clear test names to help with that.

Adjust test names

---

lib/STM_domain.mli
lib/STM_internal.mli
lib/STM_sequential.mli
lib/STM_spec.mli
lib/STM_thread.mli

This little documentation PR
- corrects a module header for `STM_internal`
- adds a module header for `STM_spec`
- corrects a typo (*an negative*)

Correct STM docs

---

src/array/dune
src/atomic/dune
src/bigarray/dune
src/bytes/dune
src/dune
src/hashtbl/dune
src/lazy/dune
src/neg_tests/dune
src/queue/dune
src/stack/dune

This PR
- adds missing test directory aliases to `src/dune`
- adds default aliases so that we build **all** tests by default (to ensure against breakage)
- annotates aliases that are currently not run, for future reference (e.g., if we want to have multiple aliases)
Overall this should fix #184 
I'm wondering if not having to interleave compiler invocations and test runs will also have an effect on #179 (CC @shym)

Add missing test aliases

---

lib/STM_internal.ml
lib/STM_spec.mli

I wonder how it came to appear, but anyway, it should go away.

Remove a weird unicode character

---

.github/workflows/common.yml
.github/workflows/linux-500-bytecode-trunk-workflow.yml
.github/workflows/linux-500-trunk-workflow.yml
.github/workflows/macosx-500-trunk-workflow.yml

The opam cache set up by `setup-ocaml` assumes that the compiler version is enough to ensure that the proper compiler is in use, but this assumption is not true for `trunk` compilers. So this adds an optional key to the common workflow so that the `cache-prefix` key is either set to v1 or to the hash of the current upstream compiler.
This also adds the benefit of logging the current commit id of the compiler used by that CI run.
Note that this PR has no impact on the Windows-CI PR, since that one always builds the OCaml compiler from sources.

CI: Set caching based on the actual upstream compiler commit

---

.github/workflows/common.yml

We see many runs on macOS failing on SIGKILL during the compilation of dependencies, which might be a sign that their build might exceed the ressources of the runner, so we remove parallelism during that phase.
The builds went ok on pushing to my fork. Let see if that works on the builds for the PR.

CI: Limit the parallelism on macOS runners

---

.github/workflows/common.yml

Setting up a full CI run for a single test is expensive: we should make the most of it by running it a couple of times, either to check for the reproducibility of a given seed or to look for seeds that produce failures.
Merging all the steps also makes logs a bit cleaner for normal runs, where only that step will be skipped.

CI configuration for running a single test

---

lib/lin.ml
lib/lin_api.ml
src/array/lin_tests.ml
src/atomic/lin_tests.ml
src/bytes/lin_tests_dsl.ml
src/hashtbl/lin_tests.ml
src/internal/cleanup_lin.ml
src/kcas/lin_tests.ml
src/lazy/lin_tests.ml
src/neg_tests/lin_tests_common.ml
src/queue/lin_tests.ml
src/stack/lin_tests.ml

This PR implements a shrinker for `multiple-ts`.
It does so by not removing any `t` variable that later commands may depend on - hence scope preservation.
Overall we replace the built-in `list` shrinker with a custom, `env`-aware shrinker. Like for the `QCheck` `list` shrinker we use the heuristic of reducing the list spine first and individual list elements (cmd arguments) second.
The spine shrinker tries
- one element after another - hence abandoning any clever bisection which shouldn't matter greatly for lists of length at most 20 `cmd`s long
- to remove non-`t` producing `cmd`s
- to remove `t`-producing `cmd`s if they are not used in the enclosing program
- to shrink `cmd` lists starting from the back - from the rationale that later `t`s are less likely to be used as fewer `cmd`s …

Scope-preserving shrinker for multiple-ts

---

doc/paper-examples/dune
doc/paper-examples/lin_tests_dsl.ml
lib/lin_domain.ml
lib/lin_domain.mli
lib/lin_effect.ml
lib/lin_effect.mli
lib/lin_thread.ml
lib/lin_thread.mli

This PR
- simplifies the `{Lin_domain,Lin_thread,Lin_effect}.Make` type annotation
- adds minimal interfaces for  `Lin_domain`, `Lin_thread`, and `Lin_effect`
- updates the doc/paper-examples/lin_tests_dsl code

More post-refactor Lin polishing

---

doc/stm/index.mld
lib/STM.ml
lib/util.ml
lib/util.mli

Sequential trace for STM tests were printed as a list, which is inconstistent with the failure message printed just below them.
This commit proposes a print_vertical function on the model of print_triple_vertical. This is the reason why the new function is placed in the Util module, despite the fact that it is only used by STM.
Fix #218

Add a print_vertical function

---

doc/util/dune
doc/util/index.mld

This PR adds a basic `Util` documentation front page as it is nice to have for consistency.
To add a bit of content I added an example.

Add a basic Util documentation front page

---

.github/workflows/common.yml
.github/workflows/windows.yml

Updating a PR will cancel all the current runs
We still keep the runs on standard push, by using `head_ref` which is defined only on PR events or falling back on `run_id` which is unique otherwise
Closes #225.

CI: Ensure at most one simultaneous run per PR

---

lib/STM.mli
lib/STM_domain.ml
lib/STM_sequential.ml
lib/STM_thread.ml
lib/lin.mli
lib/lin_domain.ml
lib/lin_domain.mli
lib/lin_effect.ml
lib/lin_effect.mli
lib/lin_thread.ml
lib/lin_thread.mli
src/array/lin_tests.ml
src/atomic/lin_tests.ml
src/hashtbl/lin_tests.ml
src/internal/cleanup.ml
src/lazy/lin_tests.ml
src/neg_tests/lin_tests_common.ml
src/neg_tests/lin_tests_effect.ml
src/neg_tests/lin_tests_thread_conclist.ml
src/neg_tests/lin_tests_thread_ref.ml
src/queue/lin_tests.ml
src/stack/lin_tests.ml

To address half of #192, set up alerts on uses of the `internal` modules and explicitly disable them on expected sites in `lib`.
This PR is split in various commits so that the alerts do show up before being disabled.

Alerts internal

---

doc/lin/dune
doc/lin/index.mld
doc/lin/mutable_set.ml
doc/lin/mutable_set_lock.ml

This documentation page takes the form of a small tutorial on the model of the one for `qcheck-stm` (PR #200). This one is a bit smaller because `qcheck-lin` is a bit simpler to use.
Participate to #168

Add a documentation page for `qcheck-lin`

---

doc/lin/dune
doc/lin/index.mld
doc/lin/mutable_set.ml
doc/lin/mutable_set_lock.ml
doc/stm/dune
doc/stm/index.mld
doc/stm/mutable_set_v0.ml
doc/stm/mutable_set_v1.ml
doc/stm/mutable_set_v2.ml
doc/stm/mutable_set_v3.ml
doc/stm/mutable_set_v4.ml
doc/stm/mutable_set_v5.ml

This PR fixes #228
Besides updating the examples and the `index.mld` files it also irons out a few things I spotted underway
- adding a missing stm example
- correcting a wrong stm test title
- breaking very long lines
- using the names of the provided test examples consistently

Use QCheck_base_runner in doc documentation

---

lib/STM.ml
src/internal/dune
src/internal/mutable_set_v5.expected
src/internal/mutable_set_v5.ml

This fixes #217 
The problem is caused by the underlying QCheck list shrinker, which cannot be both computationally fast (in the big-O sense) and complete/exhaustive. The four-element list example is bitten by this.
The PR fixes the problem by stopping the recursion a bit earlier and producing more desirable candidates for the new 3- and 4-element base cases without ruining the computational complexity (see plot below).
In addition the PR includes a few clean-ups
- to rename shrinker functions to slightly more saying names
- to eta-expand and potentially save a bit of time on a list concatenation
----
I compared the plot of the following little routine
```ocaml
let rec loop n acc = match n with
| 0 -> ()
| _ ->
Printf.printf "%3i: %!" (List.length acc);
shrink_list_spine acc (fun xs -> …
```

Adjust STM cmd list shrinker

---

.github/workflows/common.yml

Two little tweaks for the `common`-based workflows:
- add a counter when we repeat a test
- add the option to stop repeating that test at the first failure.

Two little CI tweaks

---

doc/stm/index.mld
lib/STM.mli
lib/STM_domain.mli
lib/STM_sequential.mli
lib/STM_thread.mli
lib/lin.mli
lib/lin_effect.mli

Still missing: passes over Lin tutorial and double-checking that links are actually working (using `odig doc` on locally installed packages, or is there a simpler way?).

Add some links in documentation

---

src/domain/domain_spawntree.ml

This PR fixes #202 
I added some good old `printf`-debugging to a branch and could then see the reason for the failure:
https://github.com/jmid/multicoretests/actions/runs/3605784474/jobs/6076506977
```
random seed: 530720712
generated error fail pass / total     time test name
[ ]    0    0    0    0 /  100     0.0s domain_spawntree - with Atomic
[ ]    0    0    0    0 /  100     0.0s domain_spawntree - with Atomic (generating)
[ ]    9    0    0    9 /  100    84.7s domain_spawntree - with Atomic
[ ]   30    0    0   30 /  100   169.0s domain_spawntree - with AtomicFailure - failed to allocate domains, count_spawns 936
[ ]   43    0    0   43 /  100   242.7s domain_spawntree - with AtomicFailure - failed to allocate domains, count_spawns 118
[ ]   45    0    0   45 /  100   314.0s …
```

Fix domain_spawntree test failures

---

lib/lin.ml
lib/lin.mli

The last commit of this series is really there to show what the other two add, but should probably not be included: it is probably wasting time on useless test cases.

Add `returning_ t` and constants in Lin DSL

---

src/array/dune
src/atomic/dune
src/bigarray/dune
src/buffer/dune
src/bytes/dune
src/domain/dune
src/domainslib/dune
src/ephemeron/dune
src/floatarray/dune
src/hashtbl/dune
src/lazy/dune
src/lockfree/dune
src/neg_tests/dune
src/queue/dune
src/semaphore/dune
src/stack/dune
src/thread/dune
src/threadomain/dune

This PR offers an alternative solution to the missing `(package ...)` annotations and the solution suggested in #249.
Instead it merges `(executable ...)` and `(rule ...)` stanzas into `(test ...)s`
while adding the missing `(package …)` annotations.
This has the advantage of simplifying our dune rules.

Simplify dune rules into (test ...)s and add package annotations

---

multicoretests.opam
multicoretests.opam.template

Some recursive dependency of dscheck does not build on bytecode-only OCaml so pin lockfree before that change to keep that target.
Hopefully should close #258.

Pin lockfree to the last version before dscheck dependency

---

CHANGES.md
lib/lin_domain.ml
src/internal/cleanup.ml

In domain-based test, `sut` was never cleaned-up, and so was eventually leaking resources

Cleanup resources after each domain-based Lin test

---

.github/workflows/linux-500-debug-trunk-workflow.yml
.github/workflows/linux-500-debug-workflow.yml

The debug runtime is slower than the standard runtime, so that it regularly runs out of time during CI, so give it the same timeout as other slow platforms (bytecode and windows)

Increase the timeout for the debug-runtime tests

---

.github/workflows/linux-500-bytecode-trunk-workflow.yml
.github/workflows/linux-500-bytecode-workflow.yml
.github/workflows/linux-500-debug-trunk-workflow.yml
.github/workflows/linux-500-debug-workflow.yml
.github/workflows/linux-500-trunk-workflow.yml
.github/workflows/linux-500-workflow.yml
.github/workflows/macosx-500-trunk-workflow.yml
.github/workflows/macosx-500-workflow.yml
.github/workflows/windows-500-trunk-workflow.yml
.github/workflows/windows-500-workflow.yml

First proposition to address #260. Names could be shortened further (Linux, Win, Mac, BC; tr for trunk) if need be.

Shorten workflow names by dropping (redundant) numbers

---

.github/workflows/common.yml
.github/workflows/gh-pages.yml
.github/workflows/linux-500-bytecode-workflow.yml
.github/workflows/linux-500-debug-workflow.yml
.github/workflows/linux-500-workflow.yml
.github/workflows/macosx-500-workflow.yml
.github/workflows/windows-500-workflow.yml
.github/workflows/windows.yml

This PR switched the CI from 5.0.0~rc1 to the 5.0.0 release.
It doesn't touch the (currently broken) 5.0.0+trunk workflows.

Switch CI from rc1 to 5.0.0 release

---

.github/workflows/common.yml

It was previously done only for the whole set of dependencies. Now set it up so that it's used also for ppxlib if it is pinned

CI: Set up OPAMJOBS=1 on macOS

---

.github/workflows/common.yml

In quite a few CI runs on trunk, obtaining the SHA of the tree of latest commit of the compiler fails, and so caching does something fairly unreliable. To avoid that, retry a couple of times to get that SHA1, waiting quite some time between retrials, to give github time to come back up
In the runs to try out that commit, I saw a couple of times “null”, and every time, asking a couple of times didn’t help, hence it will now the display the API answer to try and debug the issue further

CI: Retry a couple of times when getting “null“ as cache key

---

.github/workflows/common.yml

Use git ls-remote to obtain the latest commit on the followed branch, in order to avoid hitting the API-rate limit
Note that the previous strategy was using the identifier for the _tree_ rather than the _commit_, but the extra caching this allowed was probably never actually used
Follow up to #277 now that I saw that `null`s were simply due to the API-rate limit being reached.

CI: Use git ls-remote to infer a reliable cache key

---

README.md
multicoretests.opam
qcheck-lin.opam
qcheck-multicoretests-util.opam
qcheck-stm.opam

This little PR
- adds the latest two issues found by @Lucccyo and @shym 
- regenerates the included `opam` files - as the bump to dune 3.0 in #255 apparently causes changes in the output :shrug:

Add latest issues and regenerate opam files

---

lib/STM_domain.ml

While commenting on #129 I realized the `STM_domain` `retries` count is relatively high at `15`.
When combined with a `rep_count:25` for `Util.repeat` it means we end up repeating a property 15*25=375 times during shrinking for each shrinking candidate that fails!
In comparison Lin_domain uses `retries:3` and `rep_count:50` meaning it repeats a property 150 times during shrinking.
This PR therefore reduces `retries` to `10`, thus lowering shrink repetitions to `250` to avoid burning needless CPU cycles.
I have checked locally that all existing negative `STM` tests still fail with a nice and short counterexample.
For, e.g., the bytecode CI target I'm expecting/hoping this will reduce the runtime a bit.

Reduce STM_domain retries

---

src/dynlink/dune
src/dynlink/libA.ml
src/dynlink/libB.ml
src/dynlink/lin_tests_dsl.ml

This adds a (preliminary) Lin test for the `Dynlink` module, only testing three functions at the moment.
Its first run triggered a segfault on Windows in CI.

Add a (negative) Lin test for Dynlink module

---

.github/opam/custom/repo
.github/opam/ocaml-variants.opam.unix
.github/opam/ocaml-variants.opam.windows
.github/workflows/common.yml
.github/workflows/linux-501-bytecode-trunk-workflow.yml
.github/workflows/linux-501-debug-trunk-workflow.yml
.github/workflows/linux-501-trunk-workflow.yml
.github/workflows/linux-510-bytecode-trunk-workflow.yml
.github/workflows/linux-510-debug-trunk-workflow.yml
.github/workflows/linux-510-trunk-workflow.yml
.github/workflows/macosx-501-trunk-workflow.yml
.github/workflows/macosx-510-trunk-workflow.yml
.github/workflows/windows-501-trunk-bytecode-workflow.yml
.github/workflows/windows-501-trunk-workflow.yml
.github/workflows/windows-510-trunk-workflow.yml

Instead of installing a standard compiler package and later updating that opam switch with a new compiler version, generate an opam package configuration into a `local` OPAM repository
This allows to directly install the intended compiler version (a specific compiler commit, for instance) and provides caching of that compiler by setup-ocaml
The last commit of that PR should not be merged into `main` but it allows simply to test the (moving) compiler 5.0.1. (There is an OPAM package that would allow to test that compiler simply on macOS and Linux but not on Windows.)
This hopefully closes #286.

Rewrite the CI workflows to run the test suite on a specific compiler (specific commit or branch)

---

lib/lin.ml
lib/lin.mli

This PR is from @art-w's #266.
It names the individual components of `Lin.Cmd` and `Lin.Elem` which is a good idea(:tm:) independently of #266's proposed optimization.
Thanks @art-w! :smiley::pray:

Named Lin.Cmd and Lin.Elem arguments

---

lib/STM_sequential.ml
lib/lin_effect.ml
lib/lin_thread.ml

This little PR changes the 3 remaining property functions to be written using a syntactic function header.
I noticed while merging `main` into #112.
As an added bonus we avoid a little indentation :sweat_smile:

Minor code clean-up

---

src/dynlink/lin_tests_dsl.ml

The current implementation of Dynlink under Windows is not thread-safe so skip it until it is fixed

Skip Dynlink tests under Windows

---

src/domain/domain_spawntree.ml
src/thread/thread_createtree.ml

After checking in the _Introduction to Algorithms_, use the terms height and degree to bound the size of the generated trees and modify the code to match the definitions of those terms

Rename the bounds of the tree generators

---

README.md

This PR
- clarifies `opam` installation steps to reflect that we've now released the two libraries and
- tones down the 'experimental' signals in the README text

Add opam installation instructions

---

.github/workflows/common.yml
.github/workflows/linux-510-32bit-trunk-workflow.yml

Trunk OCaml now uses libzstd to compress during marshalling so we explicitly install the 32-bit version of the library in 32-bit runs and modify LDFLAGS to ensure that library is found during linking

CI: Install 32-bit libzstd for 32-bit trunk runs

---

.github/opam/ocaml-variants.opam.unix
.github/opam/ocaml-variants.opam.windows
.github/workflows/common.yml
.github/workflows/cygwin-510-trunk-workflow.yml
.github/workflows/cygwin1-510-trunk-workflow.yml
.github/workflows/cygwin2-510-trunk-workflow.yml
README.md
src/sys/stm_tests.ml

This branch is _finally_ getting mergeable.
Unfortunately, running the test suite on Cygwin takes so much time that it never fits into a single 6-hour run, so this PR proposes to add two workflows, each handling about half of the tests.
Still, I’d like to avoid repeating work as much as possible, in particular building twice the compiler and the dependencies (which take about 50 minutes in all the test rounds I ran...). So the way it is currently split up is:
- one workflow (Cygwin 1), with its `cygwin` input variable set to “initializer”, will build the compiler and the dependencies and create a cache entry with all that as soon as they are ready, before starting the tests _per se_,
- the other workflow (Cygwin 2), the “waiter”, will sleep for an hour if it does not find the cache entry …

Add workflows to test OCaml trunk on Cygwin

---

README.md

Add the race condition in accesses to the global variables storing the last error in flexdll to the list of issues found (not yet fixed)

Add the flexdll race condition to the list of issues

---

CHANGES.md
lib/STM.ml

Same problem as in #281 for `bytes` (see for instance this [run](https://github.com/shym/multicoretests/actions/runs/4469161241/jobs/7850880362#step:21:947)), so same solution.

Escape bytes when printing in STM

---

.github/workflows/common.yml
.github/workflows/windows-510-trunk-bytecode-workflow.yml

Runs with `ppxlib` no longer building with `trunk` revealed two issues that were unnoticed in the Windows workflows

Fixes small issues in CI

---

CHANGES.md
lib/STM_domain.ml
lib/STM_thread.ml

In STM_domain we use `assume (all_interleavings_ok seq_pref cmds1 cmds2 Spec.init_state)` to ensure that all `cmd` preconditions in a triple are satisfied under all interleavings.
I realize we are checking the precondition repeatedly - once for each `Util.repeat` iteration! :scream: 
By default, that means we are exploring that same exponential space 25 times whereas 1 one would do.
The PR proposes to move the precondition check outside `agree_prop_par` and the `Util.repeat` loop for both `STM_domain` and `STM_thread`.
Overall I was expecting grand CI speed-ups from this - and I encountered a few of those, e.g., `Linux trunk` in 22m31s!
Many runs however didn't speed up because of long running IO tests... I'm hoping that this together with frequency adjusted or disabled IO tests (#314) …

Avoid repetitive interleaving search in STM_domain

---

.github/workflows/cygwin-520-trunk-workflow.yml
.github/workflows/linux-520-32bit-trunk-workflow.yml
.github/workflows/linux-520-bytecode-trunk-workflow.yml
.github/workflows/linux-520-debug-trunk-workflow.yml
.github/workflows/linux-520-trunk-workflow.yml
.github/workflows/macosx-520-trunk-workflow.yml
.github/workflows/windows-520-trunk-bytecode-workflow.yml
.github/workflows/windows-520-trunk-workflow.yml
README.md

Update all the CI jobs for `trunk` so that they build OCaml 5.2, following the branching of 5.1 earlier this week.

Follow the update of trunk to 5.2

---

src/io/lin_tests_dsl_common.ml

I was looking at the `Out_channel` tests and noticed something: most of the tested operations are returning `unit` (in contrast to `In_channel` where most of them return observable values).
This decreases the chance of observing sequential consistency failures about the tested `Out_channel.t`.
This PR therefore increases the frequency of non-unit-returning functions, `pos` and `length` in `Out_channel`.
It works reasonably well: focused tests repeated 10 times triggers the expected failures on Windows and macOS as expected within the first 100-200 generated test input. We should consider this as an alternative to #314.
(Note: CI is failing on `trunk` while compiling `ppxlib` due to an AST-changing PR earlier today. The Windows `trunk` version is however based on another branch which …

Out_channel frequency adjustment

---

src/io/dune
src/io/lin_tests_dsl_domain.ml

These tests are not triggering consistently on that platform so we disable them for now

Disable the negative Out_channel tests on macOS

---

lib/STM_domain.ml
lib/STM_domain.mli
src/neg_tests/stm_tests_domain_ref.ml

This PR fixes #310 by adding an asymmetric property `agree_prop_par_asym` to `STM_domain`.
This is handy to run tests that spawn only 1 child domain to run and interpret `cmd`s in parallel with the parent domain.
To make printing of such triples nicer, the PR includes a new triple generator `STM_domain.arb_triple_asym` that has a corresponding "symmetric printer" set.
I pinned the patched version locally to see how this would help clean up the existing `ws_deque` test from `lockfree`.
For comparison, here's a diff:
```diff
diff --git a/test/ws_deque/stm_ws_deque.ml b/test/ws_deque/stm_ws_deque.ml
index fd502bc..90af0d1 100644
--- a/test/ws_deque/stm_ws_deque.ml
+++ b/test/ws_deque/stm_ws_deque.ml
@@ -63,56 +63,22 @@ end
module WSDT_seq = STM_sequential.Make (WSDConf)
module WSDT_dom = …
```

 Add agree_prop_par_asym to STM_domain

---

src/neg_tests/dune
src/neg_tests/lin_tests_common.ml
src/neg_tests/lin_tests_domain.ml
src/neg_tests/lin_tests_dsl_common.ml
src/neg_tests/lin_tests_dsl_domain.ml
src/neg_tests/stm_tests_domain_ref.ml
src/neg_tests/stm_tests_sequential_ref.ml
src/neg_tests/stm_tests_thread_ref.ml

While trying out #329 on selected parts of the test suite locally I discovered a couple of needless dependencies in src/neg_tests. This PR seeks to remove them:
- Our  `src/neg_tests/lin` `Thread` tests depended on `lin_common*` files both needlessly requiring `Domain`s - and so we move the `Lin_domain` functor applications to the `Domain`-driver files
- The `src/neg_tests/stm_tests*` had a `qcheck` dependency rather than requiring `qcheck-core` and so we switch to using `QCheck_base_runner` like the rest of the test suite.

Chore: src/neg_tests cleanups

---

src/neg_tests/stm_tests_domain_ref.ml

This little PR adjusts the test counts for the two recently added asym tests in `src/neg_tests` in an attempt to trigger them more consistently after having observed 2 failures to trigger them under Cygwin in the CI runs of #330.
Since this is for negative tests, on all other platforms the increased test count  should have no impact because a counter example will be found before getting to high counts.

Adjust asym test counts

---

.github/bin/sudo

Following ocaml/setup-ocaml#658, the invocation of apt-get changed, which broke linux CI

CI: Catch apt-get --yes install just as apt-get install

---

.github/workflows/opam.yml
README.md

In relation to #329 this PR
- updates the CI installation job to also check 4.14 (and 5.1) opam package installation
- documents the 4.14 availability in the README
To avoid triggering a entire separate CI-run for it, I include an update to set the found Flexdll issue to 'fixed'.

A few 4.14 updates

---

.github/workflows/opam.yml
dune-project
lib/lin.ml
qcheck-lin.opam

This is the change mentioned in https://github.com/ocaml-multicore/multicoretests/pull/329#issuecomment-1513515412
I've added a workflow to make sure the compatibility doesn't get broken, let me know if this is inconvenient for you.
I've opened the PR rather than waiting for edwin to come back because with the current situation, the patch is needed in order to make CI pass for https://github.com/xapi-project/xen-api/pull/4985 so I'd rather get the compatibility merged sooner rather than later

OCaml 4.13 compatibility

---

.github/workflows/opam.yml
lib/util.ml

This fixes #345 
When checking to see whether the ppx avoiding in #342 would fix the failing `opam install` from #345, I discovered that the #342's refactoring actually broke the 4.13 support just added in #340...
This PR thus 
- writes out the `Seq.equal` definition contributed in #340 
- updates the `opam install` workflow to run on all changes
The install workflows are quite fast, so I favor protecting against such breakage again now that we actually support 4.13 and 4.14.

Opam installation updates

---

.github/workflows/common.yml

This PR fixes #344 by adding the extra `libgcc-s1` dependency

Add missing dependency to get 32-bit build running again

---

README.md

This PR serves 2 purposes:
- document in the README how to run the test suite via the CI
- trigger a fresh CI run with the newly released qcheck.0.21.1 patching #348

Document CI testing options

---

.github/workflows/common.yml
.github/workflows/gh-pages.yml
.github/workflows/opam.yml

This PR bumps the used version of `actions/checkout` to v3, which apparently may improve Windows CI times a bit: https://github.com/actions/checkout/releases/tag/v3.5.1

Bump GitHub actions

---

.github/workflows/common.yml
.github/workflows/cygwin-510.yml
.github/workflows/cygwin-520-trunk.yml

The title says it all.
Log of a successful run, where the second part is skipped as intended: https://github.com/shym/multicoretests/actions/runs/5175500758
Closes #350

CI: Skip Cygwin part 2 when running only one test

---

src/sys/stm_tests.ml

This little PR
- makes the parallel `Sys` `STM` positive (not expected to fail) and
- reduces the `count` to 200
for the new shiny macOS arm64 runners.
This matches what we already do on Linux (Intel + arm64).
The PR thereby fixes #359 and helps to regain a nice all-green CI starting point.
On the branch CI run I can see this is already all green for Multicoretests-CI 
https://github.com/ocaml-multicore/multicoretests/runs/14071705952

Don't consider Sys STM tests negative on ARM64

---

CHANGES.md
lib/STM_domain.ml

I just got around to running a bit of statistics on `STM_domain.agree_prop_par_asym` for the `ref int` test.
Switching to use `Atomic` looks like a clear win when testing locally.
Over 10000 runs this represents a provable improvement at 95% confidence both when compiling to byte code:
```
$ dune exec src/statistics/z_test.exe 10000 317 10000 786
z-test of two proportions         
z = -14.527927
Is |z| = |-14.527927| > z_alpha2 = 1.960000 ?
Yes, null hypothesis rejected
```
and when compiling to native code:
```
$ dune exec src/statistics/z_test.exe 10000 785 10000 1879
z-test of two proportions         
z = -22.766211
Is |z| = |-22.766211| > z_alpha2 = 1.960000 ?
Yes, null hypothesis rejected
```
In both cases, the number of failed properties doubled!
Interestingly, native code is …

Switch STM_domain.agree_prop_par_asym to use Atomics

---

.github/workflows/cygwin-510.yml
.github/workflows/linux-510-32bit.yml
.github/workflows/linux-510-bytecode.yml
.github/workflows/linux-510-debug.yml
.github/workflows/linux-510.yml
.github/workflows/macosx-510.yml
.github/workflows/windows-510-bytecode.yml
.github/workflows/windows-510.yml

This PR moves the GitHub actions CI to test the fresh `5.1.0~beta1` release, by building on a custom Windows opam package as we've done for `5.1.0~alpha2` https://github.com/shym/custom-opam-repository/pull/1

Move GitHub actions to test 5.1.0~beta1

---

.github/workflows/common.yml
.github/workflows/cygwin-510.yml
.github/workflows/cygwin-520-trunk.yml
dune

This PR adds the possibility to use `dune` to focus on one particular test, in a similar way to what we do with github actions. This will make it easy to enable focus testing in our CI by using `dune build @@runtest ...` rather than `dune runtest ...`.
The capability was tested with CI on commit [a247a5e50f](https://github.com/shym/multicoretests/tree/a247a5e50f532206b719e2adec014ee7e11be48c) (thanks for the OPAM workflows which caught early the missing `package` annotation! :+1:).
We could imagine using that same mechanism to run focused tests also in github actions:
- Pros: this would use the same configuration across testing platforms,
- Cons: this would introduce `bash` in the testing stack on Windows / Cygwin (I don’t know whether this could introduce noise or not); this would …

Teach `dune` to focus on one particular test

---

dune
src/weak/stm_tests_hashset.ml

I just saw another occurrence failing to trigger a parallel STM Weak HashSet failure, this time under 5.1 bytecode:
https://github.com/ocaml-multicore/multicoretests/actions/runs/5488638494/jobs/10001760309
```
random seed: 192914563
generated error fail pass / total     time test name
[ ]    0    0    0    0 / 1000     0.0s STM Weak HashSet test sequential
[ ]    0    0    0    0 / 1000     0.0s STM Weak HashSet test sequential (generating)
[✓] 1000    0    0 1000 / 1000     2.7s STM Weak HashSet test sequential
================================================================================
success (ran 1 tests)
generated error fail pass / total     time test name
[ ]    0    0    0    0 / 2000     0.0s STM Weak HashSet test parallel
[ ]  742    0    0  742 / 2000    57.3s STM Weak …
```

Weak hashset adjustment

---

src/thread/thread_joingraph.ml

The PR rewrites the two separate `Atomic` and `tak` tests inside `src/thread/thread_joingraph` into one.
They were written, quick-and-dirty, over 1 year ago and large left untouched (see the git history).
This is a step toward bringing them closer to the style of the effective `src/threadomain` test.
As part of the rewrite it now occasionally triggers an explicit `Gc.minor` call.
The rewrite will make it easier to later experiment with and add additional functionality (signal raising, finalizers, ...)
If nothing else, it will also shave a couple of seconds of the test suite run time.

Thread joingraph unification (chore)

---

src/neg_tests/dune
src/neg_tests/stm_tests_domain_ref.ml
src/neg_tests/stm_tests_domain_ref_asym.ml

This PR should stabilize the output of the asym tests which have added noise since the merge of #368 that switched from `Semaphore.Binary` to an `int Atomic.t`. The end result (bumping the count) is not as exciting as the story to get there.
I first factored out the negative `asym` tests into a separate file to be sure that the state from the previous non-`asym ref` tests were not affecting the outcome, and then ran focused tests on them.
Across all architectures on both CI systems 20/20 negative tests succeeded, except for on GitHub actions, macOS 5.1 and macOS trunk:
```
macOS 5.1:     6 / 20+20  (int+int64)
macOS trunk:  15 / 20+20  (int+int64)
```
The last one had several pairs with both the int and int64 versions failing.
This prompted me to run stats using the hackish …

Refactor STM par asym tests and increment count

---

src/io/lin_tests_spec_io.ml

This PR spawned out of #373.
In `In_channel`, `bytes` are used as input buffers so only their lengths is relevant: generate and shrink them by taking only their lengths into account
It currently contains a focusing commit to remove before merging, so I set this PR as a draft.

`In_channel`: Generate and shrink bytes only on length

---

.github/workflows/common.yml
.github/workflows/cygwin-510.yml
.github/workflows/linux-510-32bit.yml
.github/workflows/linux-510-bytecode.yml
.github/workflows/linux-510-debug.yml
.github/workflows/linux-510.yml
.github/workflows/macosx-510.yml
.github/workflows/windows-510-bytecode.yml
.github/workflows/windows-510.yml

This PR switches the GitHub action workflows to test `5.1.0~rc1`.
I've created a PR against `shym/custom-opam-repository` to switch under Mingw and Cygwin https://github.com/shym/custom-opam-repository/pull/2. Until that is merged and in the interest of testing `5.1.0~rc1` the most, the PR is temporarily using the relevant branch from `jmid/custom-opam-repository`

Switch 5.1.0 workflows to rc1

---

CHANGES.md
dune
lib/util.ml
lib/util.mli
test/dune
test/util_pp.expected
test/util_pp.ml
test/util_pp_trunc150.expected
test/util_pp_trunc5.expected
test/util_pp_trunc79.expected

This PR brings a few features:
- usage of `Format` boxes to provide the same formatting as `deriving show` _and_ abide by `Format`’s rule that all content should be output into some box,
- the possibility to require the output to be truncated,
- a couple of pretty-printers that were missing,
- a couple of typo fixes.
The possibility to truncate would address #308 if all pretty-printers in `STM` and `Lin` were always using `Util.Pp` (this is #343).

Improve `Util.Pp` pretty-printers

---

CHANGES.md
lib/lin.ml
src/io/lin_tests.ml
src/io/lin_tests_spec_io.ml

This PR contains a range of adjustments to address the long shrinking sequences reported in #378:
- bf617290641d234f951600d33fa455d42256f1da and d5ff92a21ccbce6e84eb75d7d58e39cf10a8290d disable `char` element shrinking inside `bytes` and `string`s for the test
- 2433827343b1a80030dae97943fe969403cd70fe removes the `lift` combinator to reduce allocations
- ba20a6f8aee7b7aaf2a498d00345c4e2cbce2f00 adjusts the `cmd` frequencies
- 6c8db20adee709998417dd73da2ece6ff792512f drops `flush_all` entirely
- Finally e1a1de31a6cff43649e27810d804fafce3e6f256 reduces overall `Lin` allocations during `check_seq_cons` and should thus benefit other `Lin` tests too.
Overall, this makes the test behaviour reasonable. Below I include a CI summary table from running 20 focused tests across the 2 CI systems (I …

Lin Out_channel shrink cleanup

---

src/neg_tests/lin_tests_thread_ref.ml

We are seeing long `src/neg_tests/lin_tests_thread_ref.exe` causing timeouts and long runs, primarily on Cygwin part 2 (examples below).
Since the experimental `Lin` `Thread` mode does not produce test failures as consistently as the `Domain` mode, this little PR disables `cmd` argument shrinking for the test, to limit how many shrinking candidates we have to traverse.
I've run focused tests which shows runs limited to at most 771.6s on Cygwin with the fix:
- https://github.com/ocaml-multicore/multicoretests/actions/runs/6066711863/job/16457611765 5.1
- https://github.com/ocaml-multicore/multicoretests/actions/runs/6066711878/job/16457612074 trunk
Interesting observation unrelated to this PR: the first (positive test) goes from 600-800s on `5.1` to about 1200s on `trunk` (which causes the …

Disable cmd shrinking for int64 ref Thread test

---

src/neg_tests/stm_tests_thread_ref.ml

We are seeing occasional failures to trigger a `STM int64 ref Thread` negative test, e.g., here on macOS ARM64 5.0:
https://ocaml-multicoretests.ci.dev:8100/job/2023-09-04/192503-ci-ocluster-build-e5c445#L1466
```
random seed: 409068930
generated error fail pass / total     time test name
[ ]    0    0    0    0 /  250     0.0s STM int ref test with Thread
[ ]    0    0    0    0 /  250     0.0s STM int ref test with Thread (generating)
[✓]  250    0    0  250 /  250     2.9s STM int ref test with Thread
[ ]    0    0    0    0 / 1000     0.0s STM int64 ref test with Thread
[✗] 1000    0    0 1000 / 1000    11.2s STM int64 ref test with Thread
--- Failure --------------------------------------------------------------------
Test STM int64 ref test with Thread failed:
Negative test STM …
```

Increasing test count of STM int64 ref Thread test

---

.github/workflows/cygwin-510.yml
.github/workflows/linux-510-32bit.yml
.github/workflows/linux-510-bytecode.yml
.github/workflows/linux-510-debug.yml
.github/workflows/linux-510-fp.yml
.github/workflows/linux-510.yml
.github/workflows/macosx-510.yml
.github/workflows/windows-510-bytecode.yml
.github/workflows/windows-510.yml

This PR switches the 5.1.0 GitHub action workflows to `5.1.0~rc3`.
The most exiting part is spotting that `.github/workflows/linux-510-fp.yml` was using `5.1.0~rc1`... :sweat_smile: 
Almost nothing to see here, move along!

Switch 5.1.0 GitHub action workflows to 5.1.0~rc3

---

.github/workflows/cygwin-510.yml
.github/workflows/linux-510-32bit.yml
.github/workflows/linux-510-bytecode.yml
.github/workflows/linux-510-debug.yml
.github/workflows/linux-510-fp.yml
.github/workflows/linux-510.yml
.github/workflows/macosx-510.yml
.github/workflows/opam.yml
.github/workflows/windows-510-bytecode.yml
.github/workflows/windows-510.yml
README.md

As the title says, this PR bumps the 510 workflows to the 5.1.0 release.
I also spotted that the 5.1.0 opam install workflow was using `5.1.0+trunk` - which [is marked as not `available` with with 5.1.0 release](https://github.com/Octachron/opam-repository/blob/69174a86b42ba9050fd57b152dd543fb48e47924/packages/ocaml-variants/ocaml-variants.5.1.0%2Btrunk/opam#L11) causing it to fail. The PR therefore switches to 5.1.0 there too and adds an entry for `5.2.0+trunk`.
Finally, I snuck in an unrelated update to mark the framepointer `Effect` crash issue as `fixed`.

Bump 510 workflows to the 5.1.0 release

---

CHANGES.md
lib/STM.ml
lib/STM.mli
lib/STM_domain.mli
lib/STM_sequential.mli
lib/STM_thread.mli
test/dune
test/stm_next_state_exc.ml

In STM, the `next_state` function describes how the pure model description changes across each `cmd`.
As documented, ideally this function should be pure.
Surprises lurk when this is not the case, such as https://github.com/ocaml-gospel/ortac/issues/150 points 1. and 3. since
`next_state` is run both
- during generation in `gen_cmds` (sequential), `gen_cmds_size` (sequential/parallel), and `gen_triple` (parallel)
- during precondition `assert`s `cmds_ok` (sequential) and `all_interleavings_ok` (parallel)
With no generated input to print this thus yields unhelpful error messages such as:
```
ERROR: uncaught exception in generator for test STM test exception during next_state parallel after 1000 steps:
Exception: Dune__exe__Stm_next_state_exc.Random_next_state_failure
```
This PR catches …

STM: Catch exceptions in next_state for nicer UX

---

.github/workflows/linux-500-debug.yml
.github/workflows/linux-510-debug.yml
.github/workflows/linux-520-debug-trunk.yml

This little PR reduces the minor heap size of the debug-runtime workflows.
I'm expecting the reduced size to stress-test the GC-logic more than the default size.
The `s=4096` words matches that of [the ocaml/ocaml debug runtime workflow](https://github.com/ocaml/ocaml/blob/ed7b3824a260ec20a694f5070f42a7215303f8bc/.github/workflows/build.yml#L201).
Finally, the reduced size was instrumental in triggering and reproducing [the recently fixed assertion race condition](https://github.com/ocaml/ocaml/pull/12707).

Run debug-runtime workflows with a reduced minor heap

---

README.md

This little PR adds the assertion race condition issue

Add assertion race condition issue

---

.github/workflows/common.yml
.github/workflows/gh-pages.yml
.github/workflows/opam.yml

This little PR updates a couple of our GitHub Actions to the latest releases:
- `actions/checkout@v4` 
- `cygwin/cygwin-install-action@v4`
I don't expect any immediate improvement by doing so, but we may benefit from future ones by doing so.

Actions update

---

src/queue/lin_tests.ml

This PR disables the `Lin_thread` `Queue` test under bytecode which is the cause of false alarms, reported in #363.
The `Lin_thread`-mode is still experimental - and a9b2cc1f from #285 already disabled the `Stack` and `CList` ones for this reason. In view of that, this PR simply follows suit.
Fixes #363

Disable Lin_thread Queue test under bytecode

---

README.md

This PR adds the issue with the `caml_reset_young_limit` boundary case assertion.
Since https://github.com/ocaml/ocaml/pull/12742 has been merged, this PR will also serve as clean CI-rerun after the fix.

Add caml_reset_young_limit boundary case assertion issue

---

src/array/stm_tests.ml

I started going over our existing tests, and discovered a couple of `Array` entries which could easily be targeted with `STM`:
- `for_all`
- `exists` 
- `find_opt`
- `find_index`
- `stable_sort`
- `fast_sort`
Afterwards, when the 5.0 CI workflows couldn't compile, I realized that `Array.find_index` was a recent 5.1 addition.
For now, this PR therefore leaves it commented out, and so leaves us extending with 5/6 of the above.
Handling an entry conditionally will require some machinery and potentially add additional dependencies.
I don't think it is warranted to do so ATM just to target `find_index`... :shrug:

Extend STM Array tests

---

CHANGES.md
test/dune
test/mutable_set_v4.expected.32
test/mutable_set_v4.expected.64
test/mutable_set_v5.expected.32
test/mutable_set_v5.expected.64

The internal STM test `mutable_set_v5.ml` is currently run with `--verbose` which includes timing (`0.0s`) and subsequently diffed as an expect test. This creates the possibility of test failures due to a timing difference if it is run on a particular slow (CI) machine. 
I just had this happen to me on the CI of an unrelated branch which happened to take `0.1s` instead:
https://github.com/ocaml-multicore/multicoretests/actions/runs/6946194440/job/18897107446
```
STM test exception during next_state sequential failed with Random_next_state_failure as expected
STM test exception during next_state parallel failed with Random_next_state_failure as expected
diff --git a/_build/default/test/mutable_set_v5.expected b/_build/default/test/mutable_set_v5.output
old mode 100755
new mode 100644
index …
```

Strengthen mutable_set_v5 expect test against timing differences

---

.github/workflows/common.yml
.github/workflows/cygwin-51x.yml
.github/workflows/cygwin-520-trunk.yml
dune

This PR merges the two GitHub actions workflow parts for Cygwin into a single one.
Initially, the split was done out of necessity in https://github.com/ocaml-multicore/multicoretests/pull/305 and https://github.com/ocaml-multicore/multicoretests/pull/313 as the Cygwin port initially was too slow to complete within the 6h timeout!
Since then we have seen general OCaml (GC) improvements, meaning that the 2-part Cygwin CI workflow would complete in about 2x45m, and thus opening up for a workflow merge incl. saving time on storing and restoring the state.
Finally I offer two data points from a trial run of this branch:
- [`5.1.1~rc1` completed in 1h16m](https://github.com/ocaml-multicore/multicoretests/actions/runs/7142221653/job/19451051986)
- [`trunk` completed in …

Merge Cygwin CI workflow parts

---

.github/workflows/cygwin-51x.yml
.github/workflows/linux-51x-32bit.yml
.github/workflows/linux-51x-bytecode.yml
.github/workflows/linux-51x-debug.yml
.github/workflows/linux-51x-fp.yml
.github/workflows/linux-51x.yml
.github/workflows/macosx-51x.yml
.github/workflows/mingw-51x-bytecode.yml
.github/workflows/mingw-51x.yml

This PR moves the GitHub action workflows from `5.1.1~rc1` to `5.1.1`.
Since this release includes two assertion error fixes, this should take care of (some of) the failures we have been seeing.

Move GitHub action workflows to 5.1.1

---

README.md

This little PR adds the latest 2 assertion issues to the README.
While at it, it also marks two previous issues as fixed.

Add the latest assertion issues

---

src/weak/stm_tests.ml

As #406 shows, the parallel `STM Weak` test occasionally fails to trigger on s390x, thus resulting in a false alarm.
This 1-character PR therefore bumps the test `count`.
Since this is a negative test stopping on the first counterexample, all platforms except s390x should be unaffected.
On Linux/s390x this should however increase the chance of triggering the issue.

Increase count for STM Weak test parallel

---

.github/workflows/cygwin-51x.yml
.github/workflows/cygwin-520-trunk.yml
.github/workflows/cygwin-530-trunk.yml
.github/workflows/linux-51x-32bit.yml
.github/workflows/linux-51x-bytecode.yml
.github/workflows/linux-51x-debug.yml
.github/workflows/linux-51x-fp.yml
.github/workflows/linux-51x.yml
.github/workflows/linux-520-trunk-32bit.yml
.github/workflows/linux-520-trunk-bytecode.yml
.github/workflows/linux-520-trunk-debug.yml
.github/workflows/linux-520-trunk-fp.yml
.github/workflows/linux-520-trunk.yml
.github/workflows/linux-530-trunk-32bit.yml
.github/workflows/linux-530-trunk-bytecode.yml
.github/workflows/linux-530-trunk-debug.yml
.github/workflows/linux-530-trunk-fp.yml
.github/workflows/linux-530-trunk.yml
.github/workflows/macosx-51x.yml
.github/workflows/macosx-520-trunk.yml
.github/workflows/macosx-530-trunk.yml
.github/workflows/mingw-51x-bytecode.yml
.github/workflows/mingw-51x.yml
.github/workflows/mingw-520-trunk-bytecode.yml
.github/workflows/mingw-520-trunk.yml
.github/workflows/mingw-530-trunk-bytecode.yml
.github/workflows/mingw-530-trunk.yml
.github/workflows/opam.yml
README.md

This PR
- adds separate `5.3+trunk` workflows to follow `trunk`
- updates the `5.2+trunk` workflows to follow the `5.2` branch on ocaml/ocaml
Finally, to reduce CI CPU cycles, it adjusts the yaml-workflows so that pushes from me do not trigger double runs for both the push and for the PR.

Separate workflows for the 5.2 branch

---

README.md

This little PR adds the latest 3 issues
- the `Out_channel` regression
- the failure to build `dune` on `trunk`
- the abort regression on failure to create domain

Add the latest batch of issues

---

src/neg_tests/lin_internal_tests_thread_conclist.ml

OCaml's systhread context switching varies between the native and bytecode modes.
This is challenging to the experimental `Thread` modes and the package tests of it.
As a result
- both `Lin.Internal ref int/int64 test with Thread` have been disabled in bytecode mode
- the `Lin.Internal CList int64 test with Thread` has also been disabled in bytecode mode
This left `Lin.Internal CList int test with Thread` - which is marked as a positive test, but would occasionally find an unexpected counterexample in bytecode mode, causing a false alarm #358 - most recently in both `bytecode trunk` runs from #434.
This PR thus disables `Lin.Internal CList int test with Thread` in bytecode mode too.
It should eliminate another cause of false alarms.
Fixes #358

Disable 'Lin.Internal CList int test with Thread' under bytecode

---

.github/workflows/cygwin-51x.yml
.github/workflows/linux-51x-32bit.yml
.github/workflows/linux-51x-bytecode.yml
.github/workflows/linux-51x-debug.yml
.github/workflows/linux-51x-fp.yml
.github/workflows/linux-51x.yml
.github/workflows/macosx-51x.yml
.github/workflows/mingw-51x-bytecode.yml
.github/workflows/mingw-51x.yml

5.1.1 has been released for some time now, meaning there is less reason to continuously test it.
This PR therefore retires the 5.1.x workflows to run once per week, like the 5.0.0 workflows.

Reduce 51x CI runs

---

README.md

This PR
- adds the long-standing `threadomain` issue
- marks the `Out_channel` regression issue as fixed

Issue list update

---

CHANGES.md
lib/lin_domain.ml
lib/lin_domain.mli
src/README.md
src/array/lin_tests.ml
src/bigarray/lin_tests.ml
src/dynlink/lin_tests.ml
src/ephemeron/dune
src/ephemeron/lin_tests.ml
src/floatarray/lin_tests.ml
src/hashtbl/lin_tests.ml
src/io/lin_tests_domain.ml
src/lazy/lin_tests.ml
src/queue/lin_tests.ml
src/stack/lin_tests.ml
src/weak/dune
src/weak/lin_tests.ml
src/weak/lin_tests_hashset.ml

This PR adds `Lin_domain.stress_{prop,test}`
These are useful to test that parallel misuse does not cause any crashes.
For the testsuite we add stress tests of modules containing only negative parallel tests, that tend to find a counterexample fast, and hence not perform much parallel stress testing. 
While experimenting with the branch, this mode has already been useful to help create a consistent reproducer of the Dynlink issue #307.
I tried cleaning up the git-history this time, so it should read relatively cleanly @shym :wink: 
Can you give it a brief look, e.g., just the first 4 commits?

Add Lin_domain.stress_test

---

.github/workflows/cygwin-520.yml
.github/workflows/linux-520-32bit.yml
.github/workflows/linux-520-bytecode.yml
.github/workflows/linux-520-debug.yml
.github/workflows/linux-520-fp.yml
.github/workflows/linux-520.yml
.github/workflows/macosx-520.yml
.github/workflows/mingw-520-bytecode.yml
.github/workflows/mingw-520.yml

This moves our 520-workflows to target the freshly released `5.2.0~beta1`

Move 520-workflows on GitHub actions to 5.2.0~beta1

---

.github/workflows/cygwin-51x.yml
.github/workflows/cygwin-520.yml
.github/workflows/cygwin-530-trunk.yml

Earlier, we struggled with Cygwin workflows being slow.
This was a necessity in #305 and #313 as the Cygwin port initially was too slow to complete within the 6h timeout!
In #420 we then merged them into a single workflow, like the remaining targets.
This is running well, but still suffers from timeouts due to #307, adding 2 hours compared to the MinGW counterparts.
This PR therefore reduced the Cygwin workflow timeouts to 240m like the remaining workflows.

Reduce Cygwin timeouts to 240m like the remaining workflows

---

src/dynlink/lin_tests.ml

This PR temporarily disables the `Dynlink` tests under Windows as
- a fix is in the pipeline
- they are adding noise to every run
Once merged, I'll open a "reminder-PR" to reenable both of them under Windows.

Temporarily disable Dynlink tests under Windows

---

src/bigarray/dune
src/bigarray/lin_tests.ml
src/bigarray/stm_tests.ml

This PR reenables the `Bigarray` `STM` tests, the idea being that a model-based `STM` test is stricter than a `Lin` one.
A bit of background:
- `Lin` tests of `Bigarray` were added in #121
- `STM` tests of `Bigarray` were added in #125
- The `STM` `Bigarray` tests were disabled in #250 (by mistake AFAICS)
- This PR leaves stress tests of `Bigarray` using the `Lin` spec #443

Reenable Bigarray STM tests

---

src/neg_tests/stm_tests_thread_ref.ml

This failed to trigger a counterexample on macos-arm64-5.2 within 2500 iterations on the merge of #454 to `main`.

Increment count for STM int64 ref test with Thread

---

.github/workflows/macosx-arm64-500.yml
.github/workflows/macosx-arm64-51x.yml
.github/workflows/macosx-arm64-520.yml
.github/workflows/macosx-arm64-530-trunk.yml
.github/workflows/macosx-intel-500.yml
.github/workflows/macosx-intel-51x.yml
.github/workflows/macosx-intel-520.yml
.github/workflows/macosx-intel-530-trunk.yml
.github/workflows/opam.yml
README.md
src/sys/stm_tests.ml

For quite some time, GitHub actions only supported macOS on Intel hardware.
That has changed recently: https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources
Interestingly, we have used `macos-latest` which then changed hardware underneath our feet.
I noticed, because the once-per-week 5.0.0 and 5.1.1 workflows started finding an `STM` `Sys` parallel counterexample relatively consistently.
(details below)
This PR thus adds explicit macOS Intel (macos-13) and ARM64 (macos-14) workflows, thus collecting them both in the same GitHub actions CI "backend". I'll write a separate PR to remove the macOS ARM64 runners from multicoretests-ci.
Examples of the two latest runs: …

Add explicit macOS Intel+ARM64 runners

---

.github/workflows/cygwin-520.yml
.github/workflows/linux-520-32bit.yml
.github/workflows/linux-520-bytecode.yml
.github/workflows/linux-520-debug.yml
.github/workflows/linux-520-fp.yml
.github/workflows/linux-520.yml
.github/workflows/macosx-arm64-520.yml
.github/workflows/macosx-intel-520.yml
.github/workflows/mingw-520-bytecode.yml
.github/workflows/mingw-520.yml

Following https://github.com/shym/custom-opam-repository/pull/12 this PR moves the GitHub Actions workflows from `5.2.0~beta2` to the `5.2.0` release.

Move GA workflows from 5.2.0~beta2 to 5.2.0 release

---

.github/workflows/cygwin-530-trunk.yml
.github/workflows/linux-530-trunk-32bit.yml
.github/workflows/linux-530-trunk-bytecode.yml
.github/workflows/linux-530-trunk-debug.yml
.github/workflows/linux-530-trunk-fp.yml
.github/workflows/linux-530-trunk.yml
.github/workflows/macosx-arm64-530-trunk.yml
.github/workflows/macosx-intel-530-trunk.yml
.github/workflows/mingw-530-trunk-bytecode.yml
.github/workflows/mingw-530-trunk.yml
.github/workflows/msvc-530-trunk-bytecode.yml
.github/workflows/msvc-530-trunk.yml

Development of the testsuite has slowed a bit down, which means that a couple of weeks may sometimes pass without PRs to trigger a test run of trunk.
This PR therefore adds a cron-scheduled run every Monday morning.

Trigger a trunk run every Monday morning

---

CHANGES.md
lib/STM_domain.ml
lib/STM_domain.mli
lib/lin_domain.mli

This is something that I found myself wanting for testing the concurrency-sensitive module `Stdlib.Dynarray`. The new function allows to get a more intensively parallel test without much additional effort, which helps to test for parallelism-related crashes.

Add STM_domain.stress_test_par test

---

lib/STM_domain.ml
lib/STM_domain.mli
src/buffer/stm_tests.ml
src/domain/stm_tests_dls.ml
src/sys/stm_tests.ml
src/weak/stm_tests.ml
src/weak/stm_tests_hashset.ml

This PR extends the existing test suite to utilize the newly added `STM` stress tests from #462 by triggering them for modules where we presently only have an `STM` spec (and no `Lin` one):
- Buffer
- Domain.DLS
- Weak
- Weak Hashsets
To start off the Domain.DLS tests in a known good state (a fresh child Domain) the PR exposes 
`STM_domain.stress_prop_par` as a parallel to `STM_domain.stress_test_par`.
For the latter, I realize I've tried to follow an unstated naming convention (`s/test/prop/`)

Utilize STM stress test

---

.github/workflows/cygwin-520.yml
.github/workflows/linux-520-32bit.yml
.github/workflows/linux-520-bytecode.yml
.github/workflows/linux-520-debug.yml
.github/workflows/linux-520-fp.yml
.github/workflows/linux-520.yml
.github/workflows/macosx-arm64-520.yml
.github/workflows/macosx-intel-520.yml
.github/workflows/mingw-520-bytecode.yml
.github/workflows/mingw-520.yml

#461 added a weekly `trunk` CI run.
To better understand
- whether some issues show up on 5.2 but not `trunk`, e.g, #446 and
- how the testsuite outcome works across time
this PR adds corresponding scheduled 5.2 CI runs every Monday morning.

Trigger a 5.2 run every Monday morning

---

.github/runner.sh
.github/workflows/common.yml
.github/workflows/linux-500-debug.yml
.github/workflows/linux-51x-debug.yml
.github/workflows/linux-520-debug.yml
.github/workflows/linux-530-trunk-debug.yml
.github/workflows/linux-540-trunk-debug.yml
dune
src/array/dune
src/atomic/dune
src/domain/dune
src/hashtbl/dune
src/io/dune
src/lazy/dune
src/neg_tests/dune
src/queue/dune
src/stack/dune
test/dune

This PR brings a couple of small changes. In particular the main two commits are intended to make it a bit easier to upstream a workflow running the testsuite to the compiler:
- 665555c3 Define the `testsuite` and `internaltests` aliases
- 80ccd65f Silence all skipped tests
This will make it easier to run only the testsuite per se upstream, and to avoid the noise of the `Skipping ...` messages.
The other 3 commits are to use the new aliases in our CI, to let the `debug mode` message appear in debug runs and to remove an obsolete comment:
- 6662af3d Use the `testsuite` and `internaltests` aliases in CI
- cd5b374a Drop the v=0 parameter in CI debug runs
- fa43e243 Remove an obsolete comment

Small cleanups to ease upstreaming

---

CHANGES.md
lib/STM.ml
test/mutable_set_v4.expected.32
test/mutable_set_v4.expected.64
test/mutable_set_v5.expected.32
test/mutable_set_v5.expected.64

`STM_sequential` uses `Gen.sized` to generate `cmd list`s, which means the output size depends on `Gen.nat`, which may output lists of up size 10.000 with a 5% chance.
Here's are some quick stats to illustrate, here on the Domain.DLS STM test:
```
multicoretests-latest$ dune exec src/domain/stm_tests_dls.exe -- -v
random seed: 245423950
generated error fail pass / total     time test name
[✓] 1000    0    0 1000 / 1000     0.5s STM Domain.DLS test sequential
+++ Stats for STM Domain.DLS test sequential ++++++++++++++++++++++++++++++++++++++++++++++++++++++++
stats cmd length:
num: 1000, avg: 364.61, stddev: 1267.28, median 9, min 0, max 9737
0.. 486: #######################################################         856
487.. 973: ###### …
```

Reduce `STM.cmds_gen` list size

---

.github/workflows/cygwin-520.yml
.github/workflows/linux-520-32bit.yml
.github/workflows/linux-520-bytecode.yml
.github/workflows/linux-520-debug.yml
.github/workflows/linux-520-fp.yml
.github/workflows/linux-520.yml
.github/workflows/macosx-arm64-520.yml
.github/workflows/macosx-intel-520.yml
.github/workflows/mingw-520-bytecode.yml
.github/workflows/mingw-520.yml

With 5.3.0~beta1 coming out today, there is no need to continue testing 5.2 on PRs and pushes to main.
This PR thus reduces their runs to a cron job once a week.

Disable 5.2.0 tests on PRs and pushes to main

---

.github/workflows/common.yml
CHANGES.md
dune-project
lib/STM.ml
lib/lin.ml
multicoretests.opam
qcheck-lin.opam
qcheck-multicoretests-util.opam
qcheck-stm.opam
test/util_pp.expected
test/util_pp_trunc150.expected
test/util_pp_trunc79.expected

This PR bumps the qcheck-core lower bound to 0.23.
This freshly-released version means the `Util.Pp.pp_fun_` output will contain properly escaped and quoted chars and strings, and thus more comprehensible - see, e.g., the expect test diff in ef6c0067.
As an added benefit, the new lower-bound means the Lin and STM show functions can be simplified,
as they no longer need to work around QCheck.Print's lack of quoting and escaping.

Require qcheck-core.0.23

---

CHANGES.md
lib/STM.ml

This is an oversight forgotten in #491: 
`qcheck-core.0.23` includes an upstreamed `Gen.exponential` combinator (from STM even) - so we should then use it.

Use exponential

---

.github/workflows/msvc-530-trunk-bytecode.yml
.github/workflows/msvc-540-trunk-bytecode.yml

Set MSVC timeout to 240m like the other bytecode workflows

---

README.md

This PR
- mark's the backup-thread assertion failure as fixed
- add @OlivierNicole's Unboxed `Dynarray` crashing bug
- removes the initial `utop` crashing issue from the list
I added the latter initially to keep track - but 3 year's later it sticks out and has been omitted in any issue statistics :shrug:

Update issue list

---

src/dynarray/dune

Fixes #503 
By using `ocaml-config:version` from `ocamlc -config` instead of `ocaml_version` we should be able to get around having to generate a dune stanza... :crossed_fingers: 
(Note: only the first commit should be merged)

Opam-free version check in Dynarray test

---

README.md
src/README.md

This PR
- adds a mention of the `run-multicoretests` label to the front page `README` and
- adds a description of the new `Gc` test to `src/README` - which was forgotten in #469 
(I am also using this as an excuse to exercise the test suite with the Gc test merged to ensure the outcome is stable)

Two README changes

---

.github/workflows/opam.yml

We started observing opam workflow failures, e.g., on #509, due to `ubuntu-latest` switching to Ubuntu 24.04.
Switching to setup-ocaml@v3 fixes this. See https://github.com/ocaml/setup-ocaml/issues/872

Use setup-ocaml 3 for opam workflow

---

CHANGES.md
lib/STM.ml
lib/STM.mli
lib/STM_domain.ml
lib/STM_domain.mli
lib/STM_sequential.ml
lib/STM_sequential.mli
lib/STM_thread.ml
lib/STM_thread.mli

See #510.
Contrary to what #510 concluded with, I decided to introduce
- an extended `Spec` signature, `SpecExt`,
- a module of default specs, `SpecDefaults`,
- and extended functors, `STM_sequential.MakeExt`, `STM_domain.MakeExt`, and `STM_thread.MakeExt`.
The reason for this is that introducing `wrapped` variants of the various functions produced by the functors would have roughly meant duplicating all of the functions.  This approach is much more incremental and also potentially allows the `Spec` interface to the extended in the future.
The idea is that one always uses the `SpecDefaults`:
```ocaml
module MySpec = struct
include SpecDefaults
...
end
```
This way new optional specs can be added as long as `SpecDetaults` can provide default implementations of such additions.
There is [a …

Introduce extended specs to allow wrapping command sequences

---

src/bytes/lin_tests.ml

Looking at the `Lin Bytes` test I noticed an embarrasing oversight: it was using the uniform `int` generators.
- The first commit thus adjusts them to use small ones - meaning we start triggering counterexamples - and thus turning the test into a negative one. Bytes is unsafe to use in parallel after all :shrug: 
- The second commit reduces the `Thread` count to 250, like, e.g., the similar `Stack Thread` test
- The third commit adds `Bytes.set` - another unexpected oversight :grimacing: 
(In fairness the STM Bytes tests are free from both of the above oversights)
Fixes #515

Lin bytes adjustments

---

src/bytes/lin_tests.ml

Bump count for Lin Bytes Domain test

---

multicoretests.opam
multicoretests.opam.template
qcheck-lin.opam
qcheck-lin.opam.template
qcheck-multicoretests-util.opam
qcheck-multicoretests-util.opam.template
qcheck-stm.opam
qcheck-stm.opam.template

This adds the `x-maintenance-intent` opam package field for future releases

Add x-maintenance-intent

---

src/bytes/lin_tests.ml

While looking at #520 I noticed the long-running Lin Bytes test contains only few of the `Bytes` module binding.
This PR adds a bunch more. 
Adding these seem to have a positive effect on quickly reducing a counterexample, when I run this locally.
As such, it may help resolve #520.
While at it, the PR also adds a `Lin` `stress_test` of these many bindings (now well beyond what `src/bytes/stm_tests.ml` covers).

Expand on Lin Bytes test and add stress test

---

.github/workflows/common.yml

Unfortunately, this is not part of a released version yet.

CI: Update `dune` to support `trunk`

---

CHANGES.md
lib/STM_thread.ml
lib/STM_thread.mli
lib/lin_domain.mli
lib/lin_effect.mli
lib/lin_thread.ml
lib/lin_thread.mli
src/bytes/lin_tests.ml
src/io/lin_tests_thread.ml
src/neg_tests/CList.ml
src/neg_tests/dune
src/neg_tests/lin_internal_tests_common.ml
src/neg_tests/lin_internal_tests_domain.ml
src/neg_tests/lin_internal_tests_effect.ml
src/neg_tests/lin_internal_tests_thread_conclist.ml
src/neg_tests/lin_tests_common.ml
src/neg_tests/lin_tests_domain.ml
src/neg_tests/lin_tests_effect.ml
src/neg_tests/lin_tests_thread.ml
src/neg_tests/stm_tests_clist_domain.ml
src/neg_tests/stm_tests_clist_sequential.ml
src/neg_tests/stm_tests_clist_spec.ml
src/neg_tests/stm_tests_clist_thread.ml
src/neg_tests/stm_tests_thread_ref.ml
src/queue/lin_tests.ml
src/stack/lin_tests.ml

This fixes #338 - or at least gives it a good kick in the right direction.
Both `Lin_thread` and `STM_thread` are currently marked as experimental - and for good reason:
The chance of them triggering unfortunate, error-triggering `Thread` context switches is currently slim.
In hindsight, releasing them earlier - even as `experimental` - was probably premature.
Recall that a `Thread` context switch may happen
- at allocation points and
- at safepoints https://github.com/ocaml/ocaml/blob/trunk/asmcomp/polling.ml
IIUC: 
- The latter is the case for the native code backend.
- The bytecode backend instead uses a `CHECK_SIGNALS` instruction inserted in `while` and `for` loops.
- Both backends utilize a "tick thread" to context switch every 50ms to avoid starvation …

Improve context switching chance in `Lin_thread` and `STM_thread` modes

---

lib/STM_domain.ml
lib/STM_thread.ml
lib/lin.ml
lib/lin_domain.ml
lib/lin_effect.ml
lib/lin_thread.ml

Hacking on #540 I realized that the {Lin,STM}_{domain,thread,...} modes contain a number of hard-earned magic constants making these modes work reasonably well.
The constants are however
- occurring directly in the code, rather than up front and
- duplicated
The PR therefore pulls them out as documented top-level definitions.
In `Lin`, it is a bit more messy than in `STM`, as the constants are spread across both `lin.ml` and `lin_domain.ml`, ...
In `lin_effect.ml` I also decided to remove the useless `Util.repeat 1`.
None of these changes should be user-visible however.

Chore: Collect magic constants

---

README.md

As a follow-up to #541 this PR clarifies some of the requirements and recommendations
- the need for a multicore machine
- a recommendation to run the test suite tests one-after-another
Finally, as I find myself maintaining this repo, I'm using this opportunity to also tone down that aspect of the README's last line. CC: @shym

Clarify test suite recommendations in README

---

CHANGES.md
lib/lin.ml
src/bytes/lin_tests.ml

The `Lin Bytes` tests are a pain point as witnessed by #544 #541 #526 #520 #518.
This PR improves on the situation by adding a `Bytes.to_seq` target which is a known source of domain-unsafety from the `STM.domain` test, yet was missing from the `Lin` tests. This addition means the `Lin_thread` test triggers much more reliably too, so it can be turned into an appropriate negative test.
Finally, shrink time of the `Lin Bytes Domain` test is a genuine issue #520 (it just happened again today). While trying to ramp up the targeted bindings of the corresponding STM Bytes tests today, I was playing with adding a `cmd` shrinker and started seeing similar longer shrink times when I added it for
```
val Bytes.blit_string : string -> int -> t -> int -> int -> unit;
```
One problem is shrinking …

Lin bytes test fixes

---

src/bytes/lin_tests.ml

The weekly runs this morning caused all 5.2.0 runs to fail the Lin Bytes test.
This was an omission from #546:
> The new improved ™️ Thread mode utilizes Gc.Memprof support to trigger context switching. 5.3 restored Memprof, which means the thread test works well there and on trunk - both tested by CI on PRs.
I tested locally on 5.2 at some point and then forgot about it again. Given the above, I think the Lin Thread-mode test of Bytes should just be disabled on 5.2 and earlier.
This PR does exactly that.

Disable Lin Bytes test under OCaml 5.2 and earlier

---

.github/workflows/common.yml
.github/workflows/opam.yml

Fixes #539
`dune.3.18.0` is now available on the opam repo.
This rolls back the pinning needed in #531 and #538.

Remove dune pins again

---

.github/workflows/common.yml
CHANGES.md
dune-project
lib/util.ml
lib/util.mli
multicoretests.opam
qcheck-lin.opam
qcheck-multicoretests-util.opam
qcheck-stm.opam
src/bytes/stm_tests.ml

This is the extension of the `STM Bytes` test mentioned in #546.
It targets 5 more bindings from the Bytes module - a decent increase over the existing 7.
I lost momentum when I hit the many index/contains/is_valid bindings covered by `src/bytes/lin_tests.ml`... :grimacing: 
~~While writing this, I noticed that `Util.Pp` only covers up to `cst3` - and similarly for `QCheck.Gen.map{,2,3}`.~~
~~I think it would be a good idea to extend both to cover up to `{cst,map}5`.~~ :slightly_smiling_face: Edit: fixed - see below

Expand on STM Bytes test

---

.github/workflows/common.yml
.github/workflows/opam.yml

This PR removes the workaround for a trunk-incompatible dune from #550, now that a compatible dune.3.18.2 has been released.

Remove workaround for trunk-incompatible dune

---

src/dynlink/lin_tests.ml

This PR reenables the `Lin` `Dynlink` test under Windows now that https://github.com/ocaml/ocaml/pull/14032 has been merged.
With our `opam`-free test setup the flexdll.0.44 release to the opam repo is not enough.
Since the above PR has been cherry-picked to the 5.4 branch too, this PR reenables the test for > 5.3
and thus avoids inserting any `git` sub-module update workarounds... :slightly_smiling_face: 
Fixes #488

Reenable Lin Dynlink test under Windows

---

README.md
src/gc/stm_tests_spec.ml

This one-line PR is a left-over from #469. It was omitted from that one to move forward with the Gc tests.
I expect the PR to trigger the two outstanding Gc issues:
- #470 
- #480 
To avoid introducing noise in CI runs, it should be merged once these two have been resolved.

Reenable Gc.compact in Gc tests

---

CHANGES.md
lib/lin.ml
lib/lin.mli

Fixes #559 
ATM this changes two empty variant types in the interface, which is a bit annoying... :thinking:

Rework GADT index types to get Lin compiling on trunk again

---

src/weak/stm_tests_hashset_spec.ml
src/weak/stm_tests_weak_spec.ml

I recently had a fresh look at the weak array and weak hash set STM tests, and discovered a couple of things.
This PR is the outcome.
The weak array and weak hash set test originated in #214.
They've since been tweaked, e.g., in #365 which among other things switched to `int64` data for the weak hash sets test,
arguing that this was faster to shrink. As we no longer shrink the `data` this argument no longer holds.
Furthermore, the tests triggered crashes in the past with `string` `data` in #283, which was caused by a combination of race conditions and variable length memory records. This speaks for reverting and using `string`s for both tests. I've confirmed that both parallel tests can trigger segfaults on an older version (OCaml 5.0.0~alpha1) with these changes.
The PR also
- revises …

STM Weak test re-revision

---

.github/workflows/common.yml
src/floatarray/stm_tests.ml

The QCheck 0.26 release https://github.com/c-cube/qcheck/releases/tag/v0.26 changes the distribution of the `float` generator to avoid blind spots: c-cube/qcheck#350.
As we have a couple of tests with `float`s this PR bumps the QCheck version to see if we've missed anything `float`-related.

Bump QCheck to 0.26 (and fix float comparisons)

---

CHANGES.md
lib/util.ml
test/util_pp.expected
test/util_pp.ml
test/util_pp_trunc150.expected
test/util_pp_trunc5.expected
test/util_pp_trunc79.expected

In #565 I discovered that `STM` argument and result printers differed causing a negative `nan` to display as `nan` as an argument to `Set`, yet it would print as `-nan` in the result, sending me on a goose chase. #562 was another example of outputs differing slightly.
Following the principle of least surprise, this PR switches all `Util.Pp` printers for base types to use the `QCheck.Print` combinators. I believe this further makes sense, since our opam packages are named with a `qcheck` prefix.
I don't claim that, e.g., the `QCheck.Print.float` printer is perfect as witnessed by the expect test output updates (e.g., `infinity` is valid copy-pasteble OCaml, whereas `inf` is not) but I would rather have to only improve such a combinator in a single, central location.

Use `QCheck.Print` combinators in `Util.Pp` printers for consistency
