README.md

Fix wrong filename in readme

---

src/queue/lin_tests.ml
src/stack/lin_tests.ml

This PR changes the generator of function arguments used for testing folds in Stack and Queue to generate smaller integers.

Generate smaller ints in Stack and Queue function arguments

---

src/statistics/README.md
src/statistics/dune
src/statistics/z_test.ml

This PR contains a statistics script handy for deciding whether changes influence our ability to detect issues

Statistics script

---

src/lazy/lazy_lin_test.ml

This PR just cherry-picks commit d0eb430 from #70:
We should properly handle exceptions in `src/lazy/lazy_lin_test.ml`

Exception handling in Lazy lin tests

---

lib/STM.ml

This PR just removes a couple of old comments in STM.ml that I just spotted...

Remove old comments in STM.ml

---

src/statistics/README.md

Elaborate on stat tools

---

src/statistics/z_test.ml

This puts in a bit more effort to verify the input numbers to `z_test.exe`

Add more input number verification to z_test

---

README.md

This PR adds the latest two issues (Ephemeron abort and Bytes crash) that were found by the tests.

Add Ephemeron and Bytes issues

---

src/bigarray/dune
src/bigarray/lin_tests_dsl.ml

Rely on Lin_api to do the heavy lifting for those tests

Add linearizability tests for Bigarray.Array1 of ints

---

src/floatarray/dune
src/floatarray/lin_tests_dsl.ml

Rely on Lin_api to do the heavy lifting for those tests

Add linearizability tests for Float.Array

---

src/bytes/dune
src/bytes/stm_tests.ml

Testing function from Bytes module - sequential and parallel tests

Add STM tests for Bytes

---

src/bigarray/dune
src/bigarray/stm_tests.ml

Testing function from Bigarray module - sequential and parallel tests

Add STM tests for BigArray

---

src/floatarray/dune
src/floatarray/stm_tests.ml

Testing function from FloatArray module - sequential and parallel tests

Add STM tests for FloatArray

---

src/README.md

This PR updates the overview in `src/README.md` to include the latest tests of `Bigarray`, `Bytes`, and `Float.Array`.

Update src/README.md with latest additions

---

lib/util.ml
lib/util.mli

Here's a PR providing documentation for the shared `Util` module.

Document the Util module

---

lib/util.ml
src/array/dune
src/atomic/dune
src/bigarray/dune
src/buffer/dune
src/bytes/dune
src/domain/dune
src/domainslib/dune
src/domainslib/task_parallel.ml
src/ephemeron/dune
src/floatarray/dune
src/hashtbl/dune
src/internal/cleanup.ml
src/internal/dune
src/kcas/dune
src/lazy/dune
src/lockfree/dune
src/neg_tests/dune
src/queue/dune
src/queue/lin_tests_dsl.ml
src/semaphore/dune
src/stack/dune
src/stack/lin_tests_dsl.ml
src/thread/dune
src/threadomain/dune

Enable colors and reduce the noise in the logs

Prettify CI logs

---

lib/lin.ml
lib/lin_api.ml
lib/lin_api.mli
src/array/lin_tests.ml
src/atomic/lin_tests.ml
src/bigarray/lin_tests_dsl.ml
src/hashtbl/lin_tests.ml
src/internal/cleanup.ml
src/lazy/lin_tests.ml
src/neg_tests/lin_tests_common.ml
src/queue/lin_tests.ml
src/stack/lin_tests.ml

This is a draft PR to keep track of my work on getting `multiple-ts` branch ready to merge.

Multiple ts fix

---

lib/STM_spec.mli

Expand on STM's postcond state parameter

---

README.md

This PR adds the new `Weak` issue.
As a bonus it updates the status of the `Buffer` issue to `fixed` with the PR merged.

Add the Weak issue

---

.github/workflows/common.yml
.github/workflows/windows.yml

In particular bring help to trigger one-shot CI runs to torture one particular test easily.

Some CI improvements

---

doc/lin/index.mld
doc/stm/index.mld

A few more fixes in documentation

Doc fixes 3

---

README.md

This little documentation PR
- updates the status MingW `Sys.readdir` issue to `fixed`
- adds the latest `Weak` `Hashset` issue

Add Weak Hashset issue

---

README.md

Add the resolution of the bug tracked in #306

Add the Buffer.add_string race condition to the list of issues

---

.github/workflows/common.yml

Following the merge of shym/custom-opam-repository#2 this little PR reverts the temporary jmid custom repo

Revert temporary jmid custom repo

---

.github/workflows/cygwin-510.yml
.github/workflows/linux-510-32bit.yml
.github/workflows/linux-510-bytecode.yml
.github/workflows/linux-510-debug.yml
.github/workflows/linux-510.yml
.github/workflows/macosx-510.yml
.github/workflows/windows-510-bytecode.yml
.github/workflows/windows-510.yml

This little PR switches the 5.1.0 workflows to `5.1.0~rc2`

Switch 510 workflows to rc2

---

README.md

Add latest batch of issues

---

README.md

This PR adds the latest two Gc issues.
While adjusting the README I also added a Tarides pointer at the bottom.

Add Gc issues

---

README.md

As a side-effect, this PR should also kick off a CI run, hopefully turning the `trunk` CI badges green again...

Add latest deadlock issue

---

README.md

This PR batches a few README updates:
- 8fb374c1db003e1faa0fd2c2238c293bbe463291 fixes a broken README link
- c2b44f3597ee250972974681e17235a0d8368149 adds blog post pointers 
- b767819cafa60021d5eb19d22c34e35de1d31132 adds a short description of repeatability efforts for the `Thread` modes
- f2874752140d5f441b1b8c8a7768cdaee55ba5b1 adds a mention of OCSF support

Misc. README updates
